### ISSUE TITLE
sodium.secretBox.seal() function does not allow nonce to be passed as parameter

### ISSUE THREAD

**Issue by chandrakantnitt** [jedisct1/swift-sodium#103]
sodium.secretBox.seal() function does not allow nonce to be passed as parameter. Now this makes the library pretty much unusable for us as we are communicating from devices on different platform. We are using UWP flavor of the same api [https://github.com/charlesportwoodii/libsodium-uwp/tree/master/docs]. We are using SecretBox.Open(ciphertext, nonce, secretKey) from UWP to decrypt the cipher text. But in Swift there is no way to create the encrypted message using the custom nonce [to add randomness to the the encryption]. Could anyone please guide if we have a way to create the encrypted message using nonce using swift-sodium library?

**Comment by jedisct1** [comment]
In Swift, the nonce is created automatically for you.

It can be part of the ciphertext, or can be stored as a distinct object. See the different `seal()` prototypes that are available:

```swift
    public func seal(message: Data, secretKey: Key) -> Data?

    public func seal(message: Data, secretKey: Key) -> (authenticatedCipherText: Data, nonce: Nonce)?

    public func seal(message: Data, secretKey: Key) -> (cipherText: Data, nonce: Nonce, mac: MAC)?
```
