### ISSUE TITLE
Not able to use it with IOS react native project

### ISSUE THREAD

**Issue by anuragvijayvergia** [jedisct1/swift-sodium#105]
Hi I am new to ios development, I want to use libsodium to generate private and public key pair for the user on my react native app. 

I have copied the Sodium.framework from the example app and when I am trying to import I am getting an error as unable to find the module. However, I get from the docs that I have to run the dist-build/ios.sh script to generate the libsodium-ios.a file. But when I am putting that script in run script of the app I am getting following error. 

make: *** No rule to make target `distclean'.  Stop.
/Users/anurag/Library/Developer/Xcode/DerivedData/sodium-dquxckzavonrivbryatoncvgwgtv/Build/Intermediates/sodium.build/Debug-iphonesimulator/sodium.build/Script-75EC7FC31F5F46EE006E8F63.sh: line 43: ./configure: No such file or directory 

I am using xcode 8.3.3 (8E3004b).

Can someone help me out in what could be the issue here, or if I am working in totally wrong direction? 

if I am working in the wrong direction what is the correct path for integrating this. 

Thanks in advance.

**Comment by jedisct1** [comment]
Try https://github.com/lyubo/react-native-sodium
