### ISSUE TITLE
[Feature Request] Wrappers for Chacha20

### ISSUE THREAD

**Issue by alexxgarci** [jedisct1/swift-sodium#112]
What would you think of doing a wrapper for Chacha20 functions?

**Comment by jedisct1** [comment]
Hi Alex,

`sodium.secretStream.xchacha20poly1305` is already available and uses Chacha20.

But there are no wrappers for `crypto_aead`. swift-sodium tries to stick to high-level APIs whenever possible, but there are none for `crypto_aead` yet. So it would be indeed nice to have at least some wrappers for xchacha20poly1305.

I'm quite busy with other projects, but this is on my todo list. Freel free to contribute these wrappers if you can!

**Comment by alexxgarci** [comment]
By ChaCha20 I was referring to a wrapper for functions like `crypto_stream_chacha20_xor()`. If it is not possible, I will try to do it and make a fork.

**Comment by jedisct1** [comment]
I'm a bit reluctant to adding these, as they are easy to use incorrectly, and will be completely removed in libsodium 2.x

In order to deterministically generate random numbers from a seed, you can use `sodium.randomBytes.deterministic`.
