### ISSUE TITLE
importing libsodium

### ISSUE THREAD

**Issue by jamesstidard** [jedisct1/swift-sodium#115]
I know this project doesn't explicitly expose the C API of `libsodium`, though I am currently using it as such. This is mainly because of ease of use of being able to use the `Carthage` package manager to link and keep up-to-date dependancies. As well as keep all my dependancy management the same. This is my justification anyway, but I'm open to alternative suggestions of managing a libsodium dependancy in a iOS pure swift project.

So with that justification, I am currently extending `Sodium` with a few of the advanced APIs which are made available through `libsodium` such as the `ED25519` elliptic curve, `SHA256`, etc. I'm doing this as such:

```swift
import Sodium
import libsodium

extension Sodium {
    var ed25519: Ed25519 { return Ed25519() }
}

class Ed25519 {
    let seedBytes = crypto_sign_ed25519_seedbytes()
    let secretBytes = crypto_sign_ed25519_secretkeybytes()
    let publicBytes = crypto_sign_ed25519_publickeybytes()
    
    func keyPair(seed: Data) -> (secretKey: Data, publicKey: Data) {
        precondition(seed.count == seedBytes, "ed25519 key pair seed should be \(seedBytes)")
        
        return seed.withUnsafeBytes { (seedPtr: UnsafePointer<UInt8>) -> (secretKey: Data, publicKey: Data) in
            let secretKeyPtr = UnsafeMutablePointer<UInt8>.allocate(capacity: secretBytes)
            let publicKeyPtr = UnsafeMutablePointer<UInt8>.allocate(capacity: publicBytes)
            
            guard crypto_sign_ed25519_seed_keypair(publicKeyPtr, secretKeyPtr, seedPtr) == 0 else {
                fatalError("Failed to create ed25519 keypair")
            }
            
            return (
                secretKey: Data(bytes: secretKeyPtr, count: secretBytes),
                publicKey: Data(bytes: publicKeyPtr, count: publicBytes))
        }
    }
}
```

The example works as I'd expect. However, certain parts of the C API are causing a linker error such as `crypto_hash_sha256_bytes()` which raises a `symbol(s) not found for architecture x86_64` when using the same kind of import pattern as above - I've also seen this on `scryptsalsa208sha256`.

I was wondering if there is a simple fix to this which I can either specify in my projects build settings or that can be made to the `swift-sodium` project. Though, I'd understand if you wouldn't want to cater to this kind of usage.

Thanks for the project and all the language bindings you maintain.

**Comment by jedisct1** [comment]
Hi!

Deriving Ed25519 keys from a seed is already supported:

```swift
    /**
     Generates a signing secret key and a corresponding public key derived from a seed.

     - Parameter seed: The value from which to derive the secret and public key.

     - Returns: A key pair containing the secret key and public key.
     */
    public func keyPair(seed: Data) -> KeyPair?
```

If a high-level API is available, use it instead of a primitive-specific one. Functions such as `crypto_sign_ed25519_*()` are only here for backward compatibility with the NaCl API and may be eventually removed.

Scrypt and SHA256 are not used by any high-level API, and are not used by anything in the Swift wrappers either, so these functions are not compiled in (libsodium is compiled in minimal mode).

**Comment by jamesstidard** [comment]
Hi @jedisct1,

Maybe I'm trying to use the wrong library for what I'm after - as I want to be able to be explicit about which algorithms I'm using to conform to a spec. It feel wrong to go through an abstraction for that as Ed25519 may be switched out for something else at some point. For example at the point of Ed25519 potentially being replaced, I'd want my code to no longer compile instead of possibly using something else.

I'll have a look around for a alternative crypto library for Swift. Let me know if you have any suggestions.

Thanks for the quick response.

**Comment by jedisct1** [comment]
It will not be replaced! See [Shall I call crypto_generichash_blake2b or just crypto_generichash?](https://download.libsodium.org/doc/quickstart/#shall-i-call-cryptogenerichashblake2b-or-just-cryptogenerichash)

**Comment by jamesstidard** [comment]
Fair point, I should make those checks manually on major releases. I'll switch to using high-level one.

I do still need access to those backwards compatible APIs for things like Scrypt, so I may look at using `libsodium` directly not built in minimal mode.

Thanks again.
