### ISSUE TITLE
[Feature Request] Support Blake2b

### ISSUE THREAD

**Issue by kylebrowning** [jedisct1/swift-sodium#117]
Would love it if someone was able to implement blake2b hashes.

**Comment by jedisct1** [comment]
Hi Kyle,

See the [hashing functions](https://github.com/jedisct1/swift-sodium#hashing). Under the hood, they are using BLAKE2B.

**Comment by kylebrowning** [comment]
Oh geez. Now I feel dumb. Im trying to port some code from another language to Swift and I guess I dont understand how they are using the Blake2b Hashes because it seems they are working with Arrays, and not strings.

Ill dig more, thanks.

**Comment by kylebrowning** [comment]
```				
$b2b = new Blake2b();
$ctx = $b2b->init(null, 5);
$b2b->update($ctx, $key_uint8, count($key_uint8));
$b2b->finish($ctx, $key_hash);
```

They are doing stuff like this, does it make sense to you? It's php

**Comment by jedisct1** [comment]
The Swift functions deal with arrays as well. In the examples,

```rust
let message = "My Test Message".data(using:.utf8)!
```

transforms the string into an array (Data) before hashing it. And the hash functions returns an array as well, that you can then convert to hexadecimal if you want to.

**Comment by jedisct1** [comment]
I don't understand what the `5` stands for in the `init()` function. Is it the output size?

And `$key_uint8` is the input?

In that case, in swift it would look like

```swift
sodium.genericHash.hash(message: key_uint8, key: key_hash, outputLength: 5)
```

But `5` would be refused as it would be completely insecure for most real world applications. The minimum is 16.

**Comment by kylebrowning** [comment]
Yeah so this is just for validating an account is real. So its a public address, just the hast of it!. 

I got it working. @jedisct1 Thank you so much for your help!

👍

**Comment by kylebrowning** [comment]
What do you think the equivalent of 
`return nacl.sign.detached.verify(hex_uint8(hexMessage), hex_uint8(hexSignature), hex_uint8(pubKey));` is?

I've tried 

```
        let message = Data(bytes: sm)
        let publicKey = Data(bytes: pk!)
        let signa = Data(bytes: sig)
        let verify = sod.sign.verify(message: message, publicKey: publicKey, signature: signa)
```

**Comment by jedisct1** [comment]
Looks equivalent, but double-check that in the swift version, `sm`, `pk` and `sig` don't contain hex encoded data as an array.

**Comment by kylebrowning** [comment]
```
    public static func checkSig(msg: String, sig: String, account: String) {
        let sig = SwiftHex.fromHex(hex: sig).toUInt8()!
        let msg = SwiftHex.fromHex(hex: msg).toUInt8()!
        guard let ac = keyfromAccount(account: account) else {
            return
        }
        let pk = SwiftHex.fromHex(hex: ac).toUInt8()
        let size = 64
        var sm: [UInt8] = Array(repeating: 0, count: 64 + msg.count)
        var m: [UInt8] = Array(repeating: 0, count: 64 + msg.count)
        
        for i in 0..<size {
            sm[i] = sig[i]
        }
        
        for i in 0..<msg.count {
            sm[i+size] = msg[i]
        }
        let sod = Sodium()
        let message = Data(bytes: sm)
        let publicKey = Data(bytes: pk!)
        let signa = Data(bytes: sig)
        let verify = sod.sign.verify(message: message, publicKey: publicKey, signature: signa)
        
        print(verify)
        let test = sod.sign.verify(signedMessage: message, publicKey: publicKey)
        print(test)
    }
```

They [UInt] Arrays :)
