### ISSUE TITLE
Building for armv7 fails

### ISSUE THREAD

**Issue by avi-kik** [jedisct1/swift-sodium#118]
When building `swift-sodium` for armv7, one gets the following link-time failure:

```
Undefined symbols for architecture armv7:
  "___multi3", referenced from:
      _crypto_sign_ed25519_pk_to_curve25519 in libsodium-ios.a(libsodium_la-keypair.o)
      _poly1305_blocks in libsodium-ios.a(libsodium_la-poly1305_donna.o)
      _crypto_scalarmult_curve25519_ref10 in libsodium-ios.a(libsodium_la-x25519_ref10.o)
      _fe25519_mul in libsodium-ios.a(libsodium_la-x25519_ref10.o)
      _fe25519_sq in libsodium-ios.a(libsodium_la-x25519_ref10.o)
      _fe25519_tobytes in libsodium-ios.a(libsodium_la-ed25519_ref10.o)
      _fe25519_sq in libsodium-ios.a(libsodium_la-ed25519_ref10.o)
      ...
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Is there a solution besides not building the affected functions?

**Comment by jedisct1** [comment]
What XCode version are you using?

**Comment by avi-kik** [comment]
Version 9.2 (9C40b)

**Comment by jedisct1** [comment]
I'm not sure how to test that. The oldest simulator supported by that version of Xcode seems to be the iPhone 5s, that had an armv8, and the demo seems to work fine on it.

But I uploaded new precompiled libraries with a removed optimization in fd0e0478479dc3ade03417eeab05d523b1017e1f

Can you try with these?

**Comment by avi-kik** [comment]
Building for Generic iOS Device with the default settings for the project (all ARM arcs in the valid architectures list) generates the reported error.

**Comment by avi-kik** [comment]
I tested the commit, and it seems to build fine.  Thank you for the swift (pun sort of intended) turn-around.

**Comment by avi-kik** [comment]
A related issue: it also seems that building with Bitcode enabled does not work.

**Comment by jedisct1** [comment]
I never understood how it could possibly work with Bitcode enabled :) But Bitcode is apparently required to publish to the Appstore. Or maybe just for WatchOS and TVOS.

I don't remember the details, but Bitcode was originally not enabled, and people reported that it had to be enabled.

**Comment by avi-kik** [comment]
I am linking swift-sodium into another framework.  Perhaps that affects how and whether Bitcode builds will work.

**Comment by avi-kik** [comment]
The reported issue was solved.

**Comment by nebyark** [comment]
I'm getting the same error as above. @jedisct1 What's your build command for libsodium (namely ios)? I'm seeing the same armv7 issue on my fork, and I use a slightly modified version of libsodium.

**Comment by jedisct1** [comment]
Hi @neybark,

The build scripts are in the `dist-build` folder, and the one for ios is named `ios.sh`.

**Comment by nebyark** [comment]
Ah ya, I'm using that one currently. Are there any arguments you're passing to it?

**Comment by jedisct1** [comment]
None. I just run `dist-build/ios.sh`. That's on the `stable` branch.
