### ISSUE TITLE
SecretBox.open(...) fails

### ISSUE THREAD

**Issue by avi-kik** [jedisct1/swift-sodium#119]
I am sealing a message using `seal(message: Data, secretKey: Key) -> Data?`, and then trying to open it using `open(nonceAndAuthenticatedCipherText: Data, secretKey: Key) -> Data?`.

The output of `seal(...)` and the `nonceAndAuthenticatedCipherText` for `open(...)` is: `27c91407132814bec39a95d8f31139209054b15f0aad22af3480c6552ed48bf2cc29a2fa2a5f9d1da9265d56cc41268f3677bb0851014fe84bf7575c62dfd905caa3c105a0730104`.

The secret key for both calls is: `c0b8d42e7b80887959593425f9d1e73ba642f23543b3a3415566dd3c257b7324`

The open fails.

Initial debugging shows that the call to `crypto_secretbox_open_easy(...)` in `open(authenticatedCipherText: Data, secretKey: Key, nonce: Nonce) -> Data?` returns `-1`.

**Comment by avi-kik** [comment]
More information: running the following test seems to work fine, so I need to discover where I'm going wrong in the actual code.

```
        let sodium = Sodium()

        let key = sodium.secretBox.key()!
        let message = sodium.randomBytes.buf(length: 16)!

        let ciphertext: Data = sodium.secretBox.seal(message: message, secretKey: key)!

        let decryptedMessage = sodium.secretBox.open(nonceAndAuthenticatedCipherText: ciphertext, secretKey: key)!

        print("cow: \(key.hexString)")
        print("cow: \(message.hexString)")
        print("cow: \(ciphertext.hexString)")
        print("cow: \(decryptedMessage?.hexString)")

        XCTAssertEqual(message, decryptedMessage)
```

**Comment by avi-kik** [comment]
I figured it out.  Thanks for the rubber-ducky debugging.

**Comment by jedisct1** [comment]
Glad to see that you sorted it out!

Out of curiosity, what was wrong?

**Comment by avi-kik** [comment]
I was a doofus.

I used a passphrase and salt data to generate a seed, which I then used to generate a key for sealing.  I skipped the "generate a key" part on opening, and just used the seed as the key.  Which of course wouldn't work.  The correct thing to do, of course, was to drop the key generation on sealing.  It was redundant.
