### ISSUE TITLE
RFC: Is my usage correct, security-wise?

### ISSUE THREAD

**Issue by avi-kik** [jedisct1/swift-sodium#120]
I am building an iOS framework for working with the Stellar blockchain network as a client.  As with other blockchains, an account is nothing more than a public/private key-pair.  I am, naturally, using `swift-sodium` for all cryptographic functions.

Stellar likes to represent an account as a secret seed and a public key derived from that seed.  Because of this, I generate an account as follows:

1. Generate random seed data (`Sodium().randomBytes.buf(length: 32)`)
2. Create encryption key using password and salt (`pwHash.hash(outputLength: 32 ...)`)
3. Encrypt seed data (`Sodium().secretBox.seal(message: seed, secretKey: secretKey)`)
4. Save encrypted seed data and salt (saved in the keychain)

To generate the required key-pair on demand, I perform the following steps:

1. Load previously-saved encrypted seed and salt
2. Create encryption key using password and salt (`pwHash.hash(outputLength: 32 ...)`)
3. Decrypt seed (`Sodium().secretBox.open(nonceAndAuthenticatedCipherText: encryptedSeedData, secretKey: skey)`)
4. Generate ED25519 key-pair (`Sodium().sign.keyPair(seed: seed)`)

My question is, does this seem reasonable?  While I understand the fundamentals of encryption, this is my first project making use of cryptographic functions.

**Comment by jedisct1** [comment]
Hi Avi,

That looks totally fine to me!

**Comment by rcamparoML** [comment]
Hi Avi,

Im working on a project using swift-sodium to generate public/private keys. Also a I want to store my private key in the keychain. As far as I know, I need to convert the private key generated by swift-sodium to a KeySec object but I'm not having success. Could you do that ? Thanks in advance :)

**Comment by avi-kik** [comment]
Private keys are just arrays of `UInt8`.  I store them as `Data` in the keychain.
