### ISSUE TITLE
SHA256 support

### ISSUE THREAD

**Issue by avi-kik** [jedisct1/swift-sodium#123]
I know that `swift-sodium` does not expose the SHA hashing algorithms through Swift, so I am using the following code:

```
import libsodium

private func hash(data input: Data) -> Data? {
    var output = Data(capacity: 32)
    var result: Int32 = -1

    result = output.withUnsafeMutableBytes { outputPtr in
        input.withUnsafeBytes{ inputPtr in
            crypto_hash_sha256(outputPtr,
                               inputPtr,
                               UInt64(input.count))
        }
    }

    if result != 0 {
        return nil
    }

    return output
}
```

No matter what the input is, I get output with a count of zero bytes.  Am I doing something wrong?

Note: I am getting back a non-nil reference with a count of zero bytes, so the call to `crypto_hash_sha256` is not indicating failure.

**Comment by blochberger** [comment]
The error you made is `Data(capacity: 32)`. It should be `Data(count: 32)` as the `init(capacity:)` initializer only reserves capacity but does not set the length.

In addition you should use `Int(crypto_hash_sha256_bytes())` rather than hardcoding the size of the output.

**Comment by avi-kik** [comment]
Thanks so much.  I will comment again if that does not work for some reason.

**Comment by avi-kik** [comment]
As an aside, I was copying the code from `GenericHash`, so use of capacity is technically wrong there, too.

**Comment by blochberger** [comment]
I don't see capacity used there:

https://github.com/jedisct1/swift-sodium/blob/34348b9b875489c1b2e7b7c5c1638ad63dd79f5f/Sodium/GenericHash.swift#L50

**Comment by avi-kik** [comment]
You are correct.  My brain did.  I'll try and upgrade it later.
