### ISSUE TITLE
Public key from secret key

### ISSUE THREAD

**Issue by aidantwoods** [jedisct1/swift-sodium#127]
It could be that I've just missed it, but I can't seem to find an API endpoint for extracting a public key from a secret key (i.e. a Swift endpoint for `crypto_sign_ed25519_sk_to_pk`).

**Comment by jedisct1** [comment]
Hi!

`Box::keypair()` accepts an optional seed: that seed is what you can store as a secret key.

**Comment by aidantwoods** [comment]
It appears that I neglected to realise that the seed is just the first 32 bytes of the secret key, and so the keypair is reconstructable from just this information 😅

**Comment by tarun9573** [comment]
Hi jedisct1,

I am having issue on generating public key from private key.
I have first created a key pair . Lets call it KEYPAIR1.
I passed the private key in the func Sign::keypair()  as a 32 byte seed. Lets call it KEYPAIR2.

The public keys of both the keypair are different, but it should be same. Please help me out.

**Comment by blochberger** [comment]
You should generate a seed first and use the seed instead of the private key:

```swift
let sodium = Sodium()
let seed = sodium.randomBytes.buf(length: sodium.sign.SeedBytes)!
let keyPair1 = sodium.sign.keyPair(seed: seed)
let keyPair2 = sodium.sign.keyPair(seed: seed)
```

Do not use the private key as the seed, as this will not work.

**Comment by tarun9573** [comment]
Then how can i generate a public key using private key ?
