### ISSUE TITLE
AEAD API

### ISSUE THREAD

**Issue by aidantwoods** [jedisct1/swift-sodium#128]
Hello!

I'm back with another API related question. Once again, it's entirely possible I'm missing something, but I can't seem to find any AEAD functions in the library, e.g. an endpoint for `crypto_aead_xchacha20poly1305_ietf_encrypt`.

**Comment by jedisct1** [comment]
Hi!

The `secretstream` API is available, and uses XChaChaPoly under the hood, but the raw AEAD indeed as no bindings yet.

Adding them should be straightforward, though,

**Comment by umbri** [comment]
Any updates on this ?

**Comment by aidantwoods** [comment]
Closed by #131
