### ISSUE TITLE
_crypto_secretbox_xchacha20poly1305_easy ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by umbri** [jedisct1/swift-sodium#130]
I try to add support for ```SecretBox``` using ```xchacha20poly1305``` but I get this errors, I need to rebuild ```libsodium``` to include that function ?

**Comment by jedisct1** [comment]
Yes.

The precompiled libraries included here are only designed to be used with the Swift wrappers. They don't include deprecated functions.

**Comment by umbri** [comment]
Are xchacha20poly1305 functions deprecated ?

**Comment by umbri** [comment]
@jedisct1 from [docs](https://download.libsodium.org/doc/secret-key_cryptography/authenticated_encryption.html) is using ```Encryption: XSalsa20 stream cipher``` I want to add support for ```XChaCha20 stream cipher``` to swift binding, or you suggest me to use default ```XSalsa20```

**Comment by jedisct1** [comment]
Just use the default :)
