### ISSUE TITLE
SPM dependency

### ISSUE THREAD

**Issue by avi-kik** [jedisct1/swift-sodium#132]
It seems that SPM requires a 3-part version tag in order to include a package as a dependency.  I was able to import swift-sodium by adding a `0.6.0` tag in my local copy of the repo, and point my `Package.swift` to that location.  However, this is obviously suboptimal.  Could you add the same tag to this repo and either use such tags exclusively, or in conjunction with, the current two-part tags?

Thanks.

**Comment by tiwoc** [comment]
SPM uses [Semantic Versioning](https://semver.org/), so it is necessary for tags to have the MAJOR.MINOR.PATCH format. It would be great if the following releases could be tagged in this format.
