### ISSUE TITLE
Not latest version on Cocoapods?

### ISSUE THREAD

**Issue by mattk90** [jedisct1/swift-sodium#134]
Hey,
it seems that not the latest version here is on cocoapods. I have problems running this through our CI with an error:

```
ios/Pods/Sodium/Sodium/libsodium/module.modulemap:1:8: redefinition of module 'libsodium'

module libsodium {
       ^
```

I directly get the pod now with `pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium'` in order to get the latest changes, since I saw that there was a naming issue with swift and you fixed that here with this commit: https://github.com/jedisct1/swift-sodium/commit/e9ce2e11a22bf33191ee9ba89b4538246092fa4c

Is that correct? Maybe update cocoapds too?

**Comment by jedisct1** [comment]
I think what's in Cocoapods and Carthage is the latest version.

There hasn't been any new release since. What's in git is development code that might be completely broken, or more realistically, that hasn't been tested much and is still subject to change before the next actual release.
