### ISSUE TITLE
Scalar multiplication

### ISSUE THREAD

**Issue by sathishTkumar** [jedisct1/swift-sodium#136]
Is there any method exposed to perform Scalar multiplication of public and private key.
In libsodium .net version, a wrapper class is available to perform scalar multiplication
FYR, check the below snippet:

`  public static void CreateCommonKey(byte[] ReceiverPublicKey)
        {
            commonKey = ScalarMult.Mult(privateKey, ReceiverPublicKey);
        }
`

Kindly help me on this to achieve.

**Comment by jedisct1** [comment]
The name of that function is scary since you should not use the result of the point multiplication as a shared key.

Which is why a key exchange API exists in libsodium, and is available in the Swift wrapper in the `KeyExchange` class. And probably in wrappers for all other languages, too.

**Comment by sathishTkumar** [comment]
Thanks for the reply.

The host with which we are communicating is using the CreateCommonKey method (specified in my previous comment), this common key with nonce is in turn used to encrypt and decrypt the data.

How can we proceed on this?

**Comment by jedisct1** [comment]
Can you fix the code running on the host?

The absence of a scalar multiplication API in the Swift wrapper was intentionally done to prevent this (the fact that it shouldn't be directly used as a shared key is documented in the libsodium documentation, but that's another evidence that people don't read it).
