### ISSUE TITLE
Linker error in release builds

### ISSUE THREAD

**Issue by alexprogrammr** [jedisct1/swift-sodium#152]
When using the KeyPairGenerator from Sodium framework that is dynamically linked with main application, the linker dies in release builds with error that it cannot find the protocol witness table for `Sodium.Box : Sodium.KeyPairGenerator` in Sodium.

The main reason for this error is conforming an internal protocol to public class that change visibility of required properties from internal to public. For example:

```
protocol NonceGenerator {
    var NonceBytes: Int { get }
    associatedtype Nonce where Nonce == Bytes
}

public class SecretBox {
    // implementation details
}

extension SecretBox: NonceGenerator {
    public var NonceBytes: Int { return Int(crypto_secretbox_noncebytes()) }
    public typealias Nonce = Bytes
}
```

I have already find related issues with swift compiler that are marked as resolved with appropriate [pull request](https://github.com/apple/swift/pull/15735) but this fix isn't included into latest Swift 4.1 version.

Changing protocol's visibility modifiers to public in whole project will fix this error.

**Comment by aidantwoods** [comment]
Interesting find – going by the dates on some of the linked bugs (around 2016) it appears this isn't limited to Swift 4.1 either.
