### ISSUE TITLE
Bump Pod version

### ISSUE THREAD

**Issue by ismetanin** [jedisct1/swift-sodium#154]
Hi! Now when I install library as a pod I've got error `Value of type 'String' has no member 'bytes'`. Look like there is an old version in .podspec.

**Comment by kellybyrd** [comment]
It looks like there hasn't been an update to cocoapod in a while. Can you guys push the latest there?

**Comment by mattk90** [comment]
I fixed that in my PR (https://github.com/jedisct1/swift-sodium/pull/164). You can see in my commits how I solved the issue. @blochberger asked me to change some stuff but haven't had time yet. But yeah the cocoapod version hasn't been updated in a while.
