### ISSUE TITLE
Current version (0.6) fails to compile in Swift 4.2 / Xcode 10

### ISSUE THREAD

**Issue by Westacular** [jedisct1/swift-sodium#155]
The exclusive access warnings of Swift 4.1 are now errors in Swift 4.2 (https://forums.swift.org/t/upgrading-exclusive-access-warning-to-be-an-error-in-swift-4-2/12704) but it's trivial to hot fix them in 0.6

If the next major version isn't going to be released soon, I'd suggest making a 0.6.1 release with the fixes. I'll make a PR momentarily with the changes.

**Comment by aidantwoods** [comment]
I think these should have been fixed in https://github.com/jedisct1/swift-sodium/pull/137?

**Comment by Westacular** [comment]
Ah, yeah, looks like it's been fixed on master, but my PR uses 0.6 as its base, with the idea that a 0.6.1 release can be made in the meantime for anyone who wants to use both Xcode 10 _and_ a release version of swift-sodium. (But I guess if the next release of swift-sodium is happening soon, then yeah, this is moot.)

**Comment by taher-mosbah** [comment]
@jedisct1 any updates on this ?

**Comment by lmenus** [comment]
+1

**Comment by brandevnull** [comment]
+1

**Comment by ckempke** [comment]
+100  XCode 10 is now the current build of Xcode, so this is failing in production.

**Comment by mattk90** [comment]
If you import the library in your Podfile like this it should compile and work: `pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium'`

**Comment by joejune** [comment]
I can confirm that these changes fix the problems, but it would be great if there could be another release that includes these changes.  It would make it possible to have another podspec depend on swift-sodium.  @jedisct1: Would it be possible to create another release?  Here's a PR to help with the podspec file:  #167
