### ISSUE TITLE
Install via CocoaPods.

### ISSUE THREAD

**Issue by galinyonchev** [jedisct1/swift-sodium#16]
Trying to install via CocoaPods, got this message: 

[!] Unable to find a specification for `Sodium (~> 0.1)`

**Comment by jedisct1** [comment]
Report it to Cocoapods maybe? I've never used Cocoapods, so I cannot really help here.

**Comment by galinyonchev** [comment]
Well, I wrote to CocoaPods support and they told me the problem is not in CocoaPods. Here is the issue:

https://github.com/CocoaPods/CocoaPods/issues/4480

"There is no pods in the master spec repository called 'Sodium'. You should file an issue with https://github.com/jedisct1/swift-sodium that their installation instructions are incorrect.

Closing this issue as the underlying issue isn't with CocoaPods."

Could you please check it?
