### ISSUE TITLE
watchOS support

### ISSUE THREAD

**Issue by joejune** [jedisct1/swift-sodium#168]
In order to support watch OS, swift-sodium will need to include a version of `libsodium.a` that has bitcode enabled.  This ticket is related:  #165

**Comment by jedisct1** [comment]
This is an issue with libsodium itself.

**Comment by joejune** [comment]
Well, even once you have a watch-friendly version of libsodium, there is still work to create the watch framework of swift-sodium.

**Comment by joejune** [comment]
Reopening since I have the fix prepped in #169.
