### ISSUE TITLE
Install swift-sodium into Swift app.

### ISSUE THREAD

**Issue by galinyonchev** [jedisct1/swift-sodium#17]
Guys, could you please provide the exact steps to import the swift-sodium lib into a Swift app? I tried drag-and-drop the Sodium folder into my app, but it says that there is no such module when I import Sodium. I tried with CocoaPods - there was an error with it. Please, help me and provide the necessary steps.

**Comment by joshjdevl** [comment]
Similar question, is there a way to add swift-sodium as a dependency in Package.swift? I currently receive the following error

> error: The dependency graph could not be satisfied (https://github.com/jedisct1/swift-sodium.git)

**Comment by nattaponasa** [comment]
@galinyonchev  If u use swift. you must add use_frameworks! in Podfile  before pod install.

pod 'Sodium', '~> 0.1'
use_frameworks!
