### ISSUE TITLE
Xcode Error:  Missing required module 'Clibsodium'

### ISSUE THREAD

**Issue by yousefnjr** [jedisct1/swift-sodium#170]
Good morning

Getting an error when trying to use Swift-Sodium 0.7.0 in an iOS project. Here's what I'm doing:

-Getting framework via Carthage (**github "jedisct1/swift-sodium"**)
-Dragging framework into Xcode @ Embedded Binaries 
-using **import Sodium** at the top of .swift files
-Build fails, error message **Missing required module 'Clibsodium'** on the import Sodium line

This worked for me without issues in Swift 4.1 / Swift-Sodium 0.6.0, but I've been struggling since moving to 4.2. I can get it to build & run in my project by downloading the Swift-Sodium Xcode project and building the framework myself, but it won't work on both simulator and real devices if I do it that way.

If you couldn't already tell, I am not an expert lol. Any ideas?

Thanks. Swift-sodium is excellent by the way.

**Comment by keefertaylor** [comment]
Drive by comment: 

You might try installing libsodium locally on your machine? 
$ brew install libsodium

**Comment by yousefnjr** [comment]
Just tried and no dice yet. I rebuilt the framework via Carthage and re-added it, still no luck. Thanks though.

**Comment by yousefnjr** [comment]
Was able to resolve this by building the frameworks manually. I used the lipo script described in the link below to build a 'fat Sodium.framework' from the Xcode project clone. After that, I went into the debug-iphonesimulator version of the Sodium.framework, and grabbed the i386 and x86 files out of the Sodium.swiftmodule folder. I then added those files into the same folder of the 'fat Sodium.framework'. Finally I added the fat framework as an Embedded Framework into my project, and she's alive! Works on both real device and sim

Link to post with script:
https://stackoverflow.com/a/29651967/5551101

**Comment by yujiahuang** [comment]
Does this means that Sodium can no longer be installed with Carthage?

**Comment by markshiz** [comment]
It looks like this occurs when Sodium.framework is not built on the machine it is being deployed to.  Importing projects may need to add their own module definition file to find `Clibsodium` when the project is not archived on the same machine.  

See: https://stackoverflow.com/a/44793192/731285

**Comment by indutny** [comment]
For anyone fighting this, adding framework to the "General > Embedded Binaries" helped!

**Comment by OliverPearmain-Pusher** [comment]
I found that this error occurs if I move/rename the directory that contains my project (and most importantly the `Carthage` directory).  

I am guessing that there is some binary within `Carthage/Builds` that bakes in the absolute path to `libSodium-(platform}.a` when its built.

You can resolve the error by rerunning `carthage update` (which will rebuild and presumably update the baked in absolute path to its new location).

**Comment by simonpierreroy** [comment]
Here is the why and how to fix it ;) https://github.com/Carthage/Carthage/issues/2618#issuecomment-672072035
