### ISSUE TITLE
XCode 10 - Remove String bytes extension 

### ISSUE THREAD

**Issue by elodd** [jedisct1/swift-sodium#171]
Hi,

I would like to remove:

public extension String {
    var bytes: Bytes { return Bytes(self.utf8) }
}

from Bytes.swift.

If it remains then I will have a compilation failure on:

let message1 = "Message 1".bytes 

Ambiguous use of 'bytes', as it confuses the compiler.

**Comment by aidantwoods** [comment]
Would be interested to see the cited reason for ambiguity: perhaps you have another module loaded that also has a `.bytes` computed property extenstion on `String`?

You should be able to write the slightly more cumbersome: `let message1 = Bytes("Message 1".utf8)` to resolve the ambiguity at the use site.
