### ISSUE TITLE
Does not build with Xcode 10.2 beta 1, "Use of undeclared type 'crypto_generichash_state'"

### ISSUE THREAD

**Issue by Westacular** [jedisct1/swift-sodium#177]
When building with Xcode 10.2 beta 1, GenericHash.swift hits errors related to `Use of undeclared type 'crypto_generichash_state'`

The underlying issue appears to be with
```c
typedef struct CRYPTO_ALIGN(64) crypto_generichash_blake2b_state {
```

Specifically: the Swift compiler now [limits maximum type alignment size at 16](https://github.com/apple/swift/commit/c1f99b5fdb717ca6135515ac94f32a5ffdd17e34), and any C type that specifies a greater alignment requirement gets imported to Swift as `OpaquePointer`.

**Comment by lmenus** [comment]
@Westacular Have you been able to get this working?

**Comment by davidperrenoud** [comment]
I have been able to make it compile with the following changes in `GenericHash.swift`:
```swift
        // ...
        private var opaqueState: OpaquePointer
        public var outputLength: Int = 0

        init?(key: Bytes?, outputLength: Int) {
            state = UnsafeMutableRawBufferPointer.allocate(byteCount: crypto_generichash_statebytes(), alignment: 64)
            guard state.baseAddress != nil else { return nil }
            opaqueState = OpaquePointer(state.baseAddress!)
        // ...
```

All the tests pass but could someone check if this is correct?

**Comment by marwan87** [comment]
@davidperrenoud, im having the same issue, if I use your code the compiler still doesn't the line, "private var state: crypto_generichash_state" Thanks for any help.

**Comment by keefertaylor** [comment]
I have a similar error building with the non-beta Swift 5 / XCode 10.2 toolchain:

```
swift-sodium/Sodium/GenericHash.swift:17:55: error: use of undeclared type 'crypto_generichash_state'
        private var opaqueState: UnsafeMutablePointer<crypto_generichash_state>
```

**Comment by alexisbronchart** [comment]
@marwan87 are you using master?

**Comment by davidperrenoud** [comment]
@jedisct1 Could you reopen this issue?

**Comment by marwan87** [comment]
@alexisbronchart  I ended up getting it work by using 
```pod "Sodium", :git => 'https://github.com/Westacular/swift-sodium.git', :branch => 'fix_xcode10.2'```
that looks like its a good fix 
its highlighted in https://github.com/jedisct1/swift-sodium/pull/178
I think it does need to be re-opened @jedisct1 as the fix needs to be tested and merged into master. 
Im currently testing the project.

**Comment by ndizazzo** [comment]
Experiencing the same thing
