### ISSUE TITLE
Add podspec to the Cocoapods

### ISSUE THREAD

**Issue by ziogaschr** [jedisct1/swift-sodium#18]
Hello @jedisct1,
can you please push your podspec to the Cocoapods so as I can add `Sodium` as a dependency to other projects podspec?

Here is [how-to](http://guides.cocoapods.org/making/getting-setup-with-trunk.html) do it. I could do this for you, but it is your project :)

Thanks,
Chris

**Comment by adriansyah** [comment]
Hello,

I just wondering if either you or @jedisct1 has push the podspec yet ?

Cheers
Adrian

**Comment by ziogaschr** [comment]
No I haven't pushed anything. :)

**Comment by jedisct1** [comment]
It's been pushed :)
