### ISSUE TITLE
Specify curve for asymmetric crypto

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/swift-sodium#186]
Is It possible to directly specify which curve to use?

It's not clear which curve is used for the 'sealed boxes'.

thank you.

**Comment by johnalanwoods** [comment]
I guess this is pervasive, the library looks cool and easy to use, but is generic, how do you know or specify which curve/algo/cipher/hash etc is being used?

**Comment by johnalanwoods** [comment]
If using a box in Swift Sodium are you using x25519 ECDH with Salsa20 as the symmetric cipher and Poly1305 for authenticating MAC, by definition?

**Comment by jedisct1** [comment]
The`Box` API in Swift wraps the `crypto_box` API of the underlying C library.

Ditto for sealed boxes, this is the `crypto_seal` API.

You can directly refer to the documentation of the C library. Swift-Sodium doesn't implement any constructions of its own, this is a direct mapping to the C library.

**Comment by johnalanwoods** [comment]
Thank you!
