### ISSUE TITLE
Appropriate use of external entropy for Ed25519 key-pair generation

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/swift-sodium#187]
Hello,

I want to use [Apple's](https://developer.apple.com/documentation/security/1399291-secrandomcopybytes) `[SecRandomCopyBytes]` function to generate entropy that I will then use to seed Ed25519 key-pair generation on iOS/macOS. 

I prefer to use `SecRandomCopyByte` as it doesn't use Yarrow or `/dev/random` but instead a [CSPRNG](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3431.pdf) built on a FIPS complaint RNG (section 7.1):

_The module uses a FIPS 140-2 approved deterministic random bit generator (DRBG) based on a block cipher as specified in NIST SP 800-90A. The default Approved DRBG used for random number generation is a CTR_DRBG with derivation function and without prediction resistance. The module also employs a HMAC-DRBG for random number generation. Seeding is obtained by read_random (a true random number generator). read_random obtains entropy from interrupts generated by the devices and sensors attached to the system and maintains an entropy pool. The NDRNG feeds entropy from the pool into the DRBG on demand. The NDRNG provides 256-bits of entropy._

As such is this acceptable use of the seed function?
My question is, given that Ed25519 in Swift-Sodium generates 64 byte secret keys, it's still correct to seed with 32 bytes right? ( I understand the other 32 bytes are not secret).
This is my approach: 

		var bytes = Array<UInt8>(repeating: 0, count: 32)
		_ = SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes)
		let testPair = sodium.sign.keyPair(seed: bytes)

Should I instead seed with 64 bytes (instead of 32)?

Maybe we could switch the entire library to use `SecRandomCopyBytes`, it seems more secure.

P.S. `SecRandomCopyBytes` and `/dev/random` used to be synonymous however over the years their entropy source has diverged.

**Comment by jedisct1** [comment]
MacOS doesn’t use Yarrow any more. I don’t remember when this happened, but that was a very long time ago (Leopard, maybe?), even though some documentation may still have reference to it.

Still, Yarrow is totally fine when properly reseeded.

SecRandomCopyBytes doesn’t provide any extra security over arc4random() and /dev/urandom .

Ed25519 secret keys are 32 bytes. But in libsodium, a copy of the public key is concatenated to it fo two reasons. First, the public key is required for signing, so this saves CPU cycles. Then, it prevents signing from being accidentally done using a different public key, which would have catastrophic implications.

If you really want to change the libsodium RNG, there are functions for this in the library (see the documentation), but this is mainly designed for testing purposes.

**Comment by johnalanwoods** [comment]
Thank you @jedisct1!
