### ISSUE TITLE
pod spec is missing SWIFT_VERSION

### ISSUE THREAD

**Issue by rogozind** [jedisct1/swift-sodium#189]
Looks like new cocoapods 1.8.x requires swift_version to be present in pod definition.
I am getting this error trying to install the pod:

[!] Unable to determine Swift version for the following pods:

- `Sodium-library` does not specify a Swift version and none of the targets (`Pods`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

Could you release a new pod  with that version attribute present?

**Comment by jedisct1** [comment]
Would you mind submitting a pull request for this?

**Comment by rogozind** [comment]
I don't seem to have a permission to push to a branch. But the fix is just these two lines:

--- a/Sodium.podspec
+++ b/Sodium.podspec
@@ -1,6 +1,7 @@
 Pod::Spec.new do |s|
 s.name = 'Sodium'
-s.version = '0.8.0'
+s.version = '0.9.0'
+s.swift_version = '4.2'
 s.license = { :type => "ISC", :file => 'LICENSE' }
 s.summary = 'Swift-Sodium provides a safe and easy to use interface to perform 

Maybe you can make that change and put a new pod to Cocoa pods.
