### ISSUE TITLE
Package Manager - could not build Clibsodium

### ISSUE THREAD

**Issue by fortmarek** [jedisct1/swift-sodium#190]
Hey!

First off, thanks for this project :) 

Now, I wanted to add this library as a dependency to my package, but it fails with two errors:

In `Aead.swift` it can not `import Clibsodium` with this error: "Could not build Objective-C module 'Clibsodium'"

And in `Clibsodium`, I get "'sodium.h' file not found" in `shimmer.h`.

Running `brew install clibsodium` helped, but then when I try to run example app with my package on the iOS simulator, I get this error: 
"dyld: Library not loaded: /usr/local/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: Path-To-Example
  Reason: no suitable image found.  Did find:
	/usr/local/opt/libsodium/lib/libsodium.23.dylib: mach-o, but not built for iOS simulator
"

Is there something I am doing wrong? Are there any additional steps needed to add `swift-sodium` to a package that supports iOS?

**Comment by myyra** [comment]
@fortmarek I had the same issue and concluded it's not possible without major reorganization of swift-sodium.

The main issue is that SwiftPM for Xcode wants to build everything from source, and cannot import pre-built libraries from search paths.

Including the source code required to build `libsodium-*.a` would theoretically work, but I didn't have the skills to extract it from the [dist-build](/jedisct1/libsodium/tree/master/dist-build) scripts.

This was during the first or second Xcode beta though, so things might have changed.

I personally moved on to using NaCl and Scrypt, which could be easily made into cross-platform (but not nearly as optimized) C libraries that Xcode is happy to build (I wrapped the C code into a SwiftPM package for [NaCL](https://github.com/myyra/ctweetnacl) and [Scrypt](https://github.com/myyra/cscrypt)).

I'd prefer to use sodium though, so if anyone with more C/Make knowledge has ideas for extracting the source I'd be happy to contribute any SwiftPM stuff needed.

**Comment by fortmarek** [comment]
Thanks for the response @myyra - that's a shame, but I am also not proficient in C/Make enough to fix this myself ;( 

I'd be curious if anyone else has been able to integrate it via SPM, but it does not seem possible to as of now from what you have laid out.

**Comment by danielrbrowne** [comment]
@jedisct1 Can this issue be reopened? Also, given there's an open PR (#198) that seems to resolve this - is there a timeframe on this fix being released? I'm looking to integrate this to a project I maintain via SPM ideally...
