### ISSUE TITLE
Convert Ed25519ToCurve25519

### ISSUE THREAD

**Issue by PavelSakhanko** [jedisct1/swift-sodium#191]
Hi! I in Java we can use lazySodium.convertPublicKeyEd25519ToCurve25519 and lazySodium.convertSecretKeyEd25519ToCurve25519. 
How I can do this in Swift with Sodium?
Thanks!

**Comment by jedisct1** [comment]
This function doesn't exist. But the `keypairFromSeed` method exists both for signature keys and encryption keys, so you can derive both from the same seed.

**Comment by PavelSakhanko** [comment]
> This function doesn't exist. But the `keypairFromSeed` method exists both for signature keys and encryption keys, so you can derive both from the same seed.

Thanks!
