### ISSUE TITLE
Support MacOS Catalyst

### ISSUE THREAD

**Issue by DmitriyBagrov92** [jedisct1/swift-sodium#195]
Can you support compilation for macOs Catalyst?
Right now I have an error:

Showing All Issues
`In /*/Sodium/libsodium/libsodium-ios.a(libsodium_la-aead_xchacha20poly1305.o), building for Mac Catalyst, but linking in object file built for iOS Simulator, for architecture x86_64`

**Comment by jedisct1** [comment]
Probably solved by the `Clibsodium.xcframework` file.
