### ISSUE TITLE
Xcode 12 beta 3

### ISSUE THREAD

**Issue by raghavbhasin97** [jedisct1/swift-sodium#205]
Hey,
 I am running into the following error when trying to build with Xcode 12 beta 3
This only happens when compiling with a simulator. It works fine on a device.
```
Could not find module 'Sodium' for target 'arm64-apple-ios-simulator'; found: x86_64-apple-ios-simulator, x86_64
```

Wondering if it would possible to generate `libsodium-ios.a` again.

**Comment by jedisct1** [comment]
beta 4 now :)

`libsodium` now includes a script to produce a `Clibsodium.xcframework` file that includes all architectures.

I'm not sure how, but I guess this is what should replace the `libsodium-*.a` files.
