### ISSUE TITLE
Sodium breaks SwiftUI Previews.

### ISSUE THREAD

**Issue by Priva28** [jedisct1/swift-sodium#208]
Hi! Sodium is working great so far and I've finally got it working with iOS, Catalyst and Simulators but have one last problem. SwiftUI Previews. For whatever reason, it seems that it needs the x86_64 and arm64 builds simultaneously or something. I'm no expert with this stuff so not really sure how to go about fixing this. 

The error is `linker command failed with exit code 1 (use -v to see invocation)`

Followed by this long error: 
```
Build target Sodium:
note: '/Users/christian/Desktop/project/Sodium/Clibsodium.xcframework' is missing architecture(s) required by this target (arm64), but may still be link-compatible. (in target 'Sodium' from project 'project')
note: '/Users/christian/Desktop/project/Sodium/Clibsodium.xcframework' is missing architecture(s) required by this target (arm64), but may still be link-compatible. (in target 'Sodium' from project 'project')


Link Sodium (arm64):
ld: warning: ignoring file /Users/christian/Library/Developer/Xcode/DerivedData/project-bwtcizhpqsiicrglmfhbuauaincz/Build/Intermediates.noindex/Previews/project/Products/Debug-iphonesimulator/libsodium.a, missing required architecture arm64 in file /Users/christian/Library/Developer/Xcode/DerivedData/project-bwtcizhpqsiicrglmfhbuauaincz/Build/Intermediates.noindex/Previews/project/Products/Debug-iphonesimulator/libsodium.a (2 slices)
Undefined symbols for architecture arm64:

****It lists all the libsodium headers here and I don't think there's any point adding it here as it'd just make the issue really long.****

Link project (x86_64):
ld: framework not found Sodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Link project (arm64):
ld: framework not found Sodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If you'd like to reproduce the error, all you need to do is add a SwiftUI view to the iOS Example in the source code, then try to open the preview. You should see 100s of undefined symbol errors. 

Hopefully someone can help,
Thanks!

**Comment by jedisct1** [comment]
Hi!

> `...ediates.noindex/Previews/project/Products/Debug-iphonesimulator/libsodium.a`

This file doesn't exist any more. Are you using the current version from this repository?

I'm also pretty sure that arm64 builds are present since the files have been created on a DTK :)

**Comment by Priva28** [comment]
My installation method is a little weird but I don't see why it wouldn't work. Because I would prefer not to use CocoaPods, and SPM didn't work, I have created a seperate Sodium framework target then copied all of the Swift source files manually (from the latest commit), along with the Clibsodium.xcframework and this seems to be working. 

Either way, I have created a test project to try using a CocoaPods install and the error (while slightly different) still occurs. I can build just fine on every other target except it doesn't work when using SwiftUI Previews.

Here is the full error this time:
```
SchemeBuildError: Failed to build the scheme "sodiumtest"

linker command failed with exit code 1 (use -v to see invocation)

Build target Sodium:
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99. (in target 'Sodium' from project 'Pods')


Link Sodium (arm64):
ld: in /Users/christian/Desktop/sodiumtest/Pods/Sodium/Sodium/libsodium/libsodium-ios.a(libsodium_la-aead_xchacha20poly1305.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Link sodiumtest (arm64):
ld: framework not found Sodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Link sodiumtest (x86_64):
ld: framework not found Sodium
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Priva28** [comment]
Hmm seems like this may be an Apple issue. https://developer.apple.com/forums/thread/657913. The solution is to exclude arm64 from build architectures, but then this means running on device won't work. I wonder if it would work without this workaround for Apple Silicon?

**Comment by Priva28** [comment]
If anyone else is having this problem here is a somewhat ok solution for now:
1. Create a new build Configuration for your project and call it "Previews". `YourProject > Info > Configurations`
<img width="526" alt="Screen Shot 2020-09-03 at 1 24 38 pm" src="https://user-images.githubusercontent.com/40876121/92067915-d336c900-ede8-11ea-8458-0cea42b382a7.png">

2. For your app **and** the Sodium target, go to `Build Settings > Architecture > Excluded Architectures` then expand it and add `arm64` for the new configuration you created.
<img width="432" alt="Screen Shot 2020-09-03 at 1 24 09 pm" src="https://user-images.githubusercontent.com/40876121/92067879-c1552600-ede8-11ea-8ff3-53f653946333.png">

3. Now go to `Manage Schemes > YourApp` then select the gear and duplicate
<img width="162" alt="Screen Shot 2020-09-03 at 1 25 22 pm" src="https://user-images.githubusercontent.com/40876121/92067949-ee093d80-ede8-11ea-8449-3624db09ea4e.png">
<img width="186" alt="Screen Shot 2020-09-03 at 1 25 50 pm" src="https://user-images.githubusercontent.com/40876121/92067973-feb9b380-ede8-11ea-91fb-e9195cb5aef5.png">

4. Then edit and change the build configuration to the one you created.
<img width="538" alt="Screen Shot 2020-09-03 at 1 26 57 pm" src="https://user-images.githubusercontent.com/40876121/92068031-26a91700-ede9-11ea-92b9-c5770056ba5f.png">

Now whenever you want to use previews, simply just select your new scheme and it will compile! When you want to use the simulator or your device, switch back to the original scheme.

**Comment by jedisct1** [comment]
Adding a "me too" on that thread so that the bug gets Apple developers' attention can be also be useful.

We've seen really bad regressions introduced in Xcode beta versions that eventually went into releases (such as the alignment bug in Xcode 10), so the more exposure actual bugs (vs regular questions) get in the dev forums, the better :)
