### ISSUE TITLE
Xcode 12 simulator issue

### ISSUE THREAD

**Issue by dev4jam** [jedisct1/swift-sodium#209]
Xcode 12 doesn't compile project with libsodium for simulator: 

ld: in XXXXXX/Pods/Sodium/Sodium/libsodium/libsodium-ios.a(libsodium_la-aead_xchacha20poly1305.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64

**Comment by dev4jam** [comment]
Resolved by adding: config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES' into Podfile

**Comment by ph4r05** [comment]
I have the same problem as a pod author. I had to add:

```
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64', 'ONLY_ACTIVE_ARCH' => 'YES', 'VALID_ARCHS' => 'armv7 arm64 x86_64' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64', 'ONLY_ACTIVE_ARCH' => 'YES' }
```

**Comment by yusufpinar048** [comment]
In which file do we add this code?
