### ISSUE TITLE
Failed to install via Carthage

### ISSUE THREAD

**Issue by adriansyah** [jedisct1/swift-sodium#22]
I try to do install swift-sodium via carthage

I use this on my Cartfile:
github "jedisct1/swift-sodium" == 0.1

Below is the error that appear

carthage update
*** Cloning swift-sodium
*** Checking out swift-sodium at "0.1"
*** xcodebuild output can be found in /var/folders/qr/rsdx9s_91b15fx_lzfy5yfwh0000gw/T/carthage-xcodebuild.mRnTvx.log
Failed to discover shared schemes in project Sodium.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/jedisct1/swift-sodium/issues/new

**Comment by jedisct1** [comment]
Should be good now!
