### ISSUE TITLE
iOS minimum deployment target

### ISSUE THREAD

**Issue by jonurq** [jedisct1/swift-sodium#221]
Hi! We use Sodium lib and our app has minimum deployment target iOS 10. 
I saw in this commit an update of this configs: https://github.com/jedisct1/swift-sodium/commit/a163995c209e7a429fecbb8c54bee649517b7b58

There is a chance to continue support from iOS 10 and above?

@jedisct1

**Comment by jedisct1** [comment]
Xcode is insisting on updating the configuration with these changes.

But that may be for a good reason: [since March 2019](https://developer.apple.com/news/?id=09122018c), Apple is refusing all new submissions and updates of applications built with an SDK older than 12.

So, I'm just following what Apple says we should do :)

**Comment by jonurq** [comment]
@jedisct1 Thanks for your response. I think that you missunderstood the apple article.
https://stackoverflow.com/a/55496726

It could be submit apps with support for iOS 8.0 and above but built in iOS 12 SDK.

 Thanks :)

**Comment by jedisct1** [comment]
Ah, thanks for clarifying!

But why does Xcode want 12 want these updates to the configuration to be made?

**Comment by jonurq** [comment]
Xcode 12 shows an error or warning?

**Comment by jedisct1** [comment]
Warning, but there has to be a reason.

**Comment by danielrbrowne** [comment]
That Apple link refers to the “Base SDK” settings. The commit linked to changes the “Deployment target” settings.

The Base SDK is the version of the OS which the code is built against (I.e what the Apple support link refers to). The deployment target is the minimum version of the OS which the library supports.

The two things are related but not equivalent. It is entirely possible to have a library built with a version of Xcode which includes a recent iOS SDK, but that supports back to an earlier deployment target version such as 9.0 (Xcode 10 will include the iOS 12 SDK for instance, so the article is essentially saying builds using Xcode 10 and above are only accepted).

**Comment by danielrbrowne** [comment]
The warning for the recommended project settings tends to (when auto fixed) increase the deployment target settings arbitrarily. I’ve not actually checked out the changes but I think you could change the deployment targets back to their original values without an issue and leave all other project changes in place.
