### ISSUE TITLE
A new tagged release for tvOS support & Carthage fixes

### ISSUE THREAD

**Issue by danielrbrowne** [jedisct1/swift-sodium#222]
Is a tagged release containing the recent tvOS support changes that I pushed in the works?

A new tagged release is also relevant since the 0.9.0 tag (and also the HEAD of `master`) does not work in my testing when integrating via Carthage, whereas the 0.8.0 tag does work with Carthage.

- [ ] A tagged release based on changes to ensure the HEAD of `master` builds when installing via Carthage.
- [ ] Also release the new tagged version via Cocoapods.

**Comment by danielrbrowne** [comment]
@jedisct1 FYI, this is the Carthage error in Terminal that I referred to when using the HEAD of `master` using Xcode 12.1:
```
*** Building scheme "Sodium" in Sodium.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/pusher/Documents/GitHub/pusher-websocket-swift/Carthage/Checkouts/swift-sodium/Sodium.xcodeproj -scheme Sodium -configuration Release -derivedDataPath /Users/pusher/Library/Caches/org.carthage.CarthageKit/DerivedData/12.1_12A7403/swift-sodium/master -sdk iphonesimulator -destination platform=iOS\ Simulator,id=C90709FF-9E06-43B3-8E97-F8EF5A9E9D17 -destination-timeout 3 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/pusher/Documents/GitHub/pusher-websocket-swift/Carthage/Checkouts/swift-sodium)
```

Here's a snippet from the Carthage build log itself:
```
CompileSwift normal x86_64 (in target 'Sodium_iOS' from project 'Sodium')
[TRIMMED FOR BREVIETY] 
/Users/pusher/Documents/GitHub/pusher-websocket-swift/Carthage/Checkouts/swift-sodium/Sodium/KeyExchange.swift:2:8: error: no such module 'Clibsodium'
import Clibsodium
       ^

** BUILD FAILED **
```

**Comment by jedisct1** [comment]
I can tag a new release, but would that fix your issues with Carthage?

**Comment by danielrbrowne** [comment]
@jedisct1 No it wouldn't I'm afraid. I'm unsure as to the reasons why but there's some difference between the 0.8.0 tag (where Carthage works) and the HEAD of `master` where it's broken currently.

Essentially, I'm trying to get to a point where the following are all true for a new tagged release:
- tvOS support is included (by virtue of already being merged to `master`)
- SPM integration works (I believe this is already the case since the 0.9.0 tag, but worth verifying before tagging a new release).
- Carthage integration works once again

**Comment by jedisct1** [comment]
Any reason you can't use the Swift package?

**Comment by danielrbrowne** [comment]
I would use SPM if absolutely necessary, but the codebase I work on uses Carthage currently and I'd rather not change it. IMHO the fact Carthage support broke between the 0.8.0 and 0.9.0 releases is a bug (I can't find any reference to it being removed intentionally).

**Comment by danielrbrowne** [comment]
However, if the Carthage integration proves difficult to resolve, then a new tagged release including the tvOS support would be very helpful :) (Also released to Cocoapods at the same time). I'll spend some time my end trying to diagnose why Carthage can't see the Clibsodium module when building...

**Comment by jedisct1** [comment]
Likely related: https://github.com/Carthage/Carthage/issues/3019

**Comment by jedisct1** [comment]
And https://medium.com/@quentinfasquel/carthage-issues-xcode-12-xcframeworks-apple-silicon-etc-1c60d8635dbc
