### ISSUE TITLE
Support for server side swift (Linux)

### ISSUE THREAD

**Issue by code28** [jedisct1/swift-sodium#224]
Using this new construct with libsodium shipped in the `Clibsodium.xcframeworks`, server side swift isn't supported anymore. When compiling, this error message occurs:
```
error: artifact 'Clibsodium' does not support the target platform and architecture ('Triple(tripleString: "x86_64-unknown-linux-gnu", arch: SPMBuildCore.Triple.Arch.x86_64, vendor: SPMBuildCore.Triple.Vendor.unknown, os: SPMBuildCore.Triple.OS.linux, abi: SPMBuildCore.Triple.ABI.unknown)')
```
We are using Sodium on our Swift server, which wasn't a problem before and everything worked well by installing libsodium globally.
It'd be great to have support for `x86_64-unknown-linux-gnu` architecture with this construct as well. Is this planned?

**Comment by jedisct1** [comment]
Do you know how to do that?

**Comment by code28** [comment]
I guess that the file [dist-build.sh](https://github.com/jedisct1/libsodium/blob/master/dist-build/apple-xcframework.sh) just needs to get another architecture - `x86_64-unknown-linux-gnu` - and the `xcframework` needs to be updated in this repo. I think, that should be enough. You are probably way more aware of what to write in that file, and I suppose it shouldn't be a lot of lines. Or do you see something, which could add complexity?

I'm happy to help further where I can - especially with trying, if it works.

**Comment by jedisct1** [comment]
But how do you compile to Linux? Using Zig maybe?

**Comment by code28** [comment]
Ah, I see what you mean. Actually didn't think about it before... I don't know a lot about Zig, so I don't know if it could help, but this could be done quite easily using Docker. This adds some overhead, because Docker must be installed, but otherwise, it should be quite easy:

Dockerfile:
```Dockerfile
FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true \
    && apt-get -q update \
    && apt-get -q dist-upgrade -y\
    && apt-get install -y curl build-essential\
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY . .
CMD \
  make distclean >/dev/null 2>&1 \
  ./configure && \
  make install || exit 1
```

In `apple-xcframework.sh`:
```shell
docker build -t libsodium-docker-builder .
docker run --rm -v `pwd`:/tmp libsodium-docker-builder
docker image rm libsodium-docker-builder:latest
```

This will create a docker image, which compiles libsodium. Using `-v` on `docker run`, those files can be extracted out of the docker container to the host.

I didn't test that yet, but something like this might work. If you think, it's worth elaborating, I'll try to make it work. I could need  some help, which flags should be used to build and which files are needed.

**Comment by jedisct1** [comment]
I managed to get the library compiled to `x86_64-linux-gnu` and `aarch64-linux-gnu` as part of the `apple-xcframework.sh` script, but `xcodebuild -create-xcframework` doesn't seem to support non-Mach-O libraries:

```text
error: unable to find any architecture information in the binary at '/Users/j/src/libsodium/libsodium-apple/tmp/linux-gnu-aarch64-linux-gnu/lib/libsodium.a': Unknown header: 0x464c457f
```

How is it possible to add support for other libraries in a xcframework?

**Comment by code28** [comment]
Oh no... actually, I thought, this should just work, because it just looked like an enumeration of binary libraries. Unfortunately, xcframeworks (and binary targets in SPM) seem to only support Apple platforms for now. So maybe we need something like #225 until linux support is added for binary targets in SPM.

**Comment by code28** [comment]
@jedisct1 Thanks for merging #224! For me, this issue can be closed, because the issue is resolved.
Could you tag a new release for that, so that it can be used again? Thanks!

**Comment by FabioTacke** [comment]
Any updates on the new release? I would really like to update my dependencies to use the linux fix.
