### ISSUE TITLE
Support distributing swift-sodium as XCFramework

### ISSUE THREAD

**Issue by simonpierreroy** [jedisct1/swift-sodium#227]
I am trying to distribute this project as an XCFramework and I am having some issues. 

The project archives properly and I am able to create the XCFramework, but I cannot use it since the `.swiftinterface` contains a reference to the internal `Clibsodium` and this is not available once archived (`No such module 'Clibsodium'`). 

I tried to manually update the `module.modulemap` inside the XCFramework to expose back the interface and the `Clibsodium` module, but with no luck. Any ideas on how to that?

I was also considering using `@_implementationOnly import Clibsodium ` to fully hide Clibsodium inside `Sodium` and remove it from the final `.swiftinterface`. (Making no types from Clibsodium public and creating wrapper types)

Here is the compile project as an XCFramework that I am not able to use.

[Sodium-3c10d39e0ead653ba980b6c64b6d4e5493ac64d9-Xcode_12.2_Build_version_12B45b.xcframework.zip](https://github.com/jedisct1/swift-sodium/files/5645158/Sodium-3c10d39e0ead653ba980b6c64b6d4e5493ac64d9-Xcode_12.2_Build_version_12B45b.xcframework.zip)

I would love to find a way to create an XCFramework for this project, thank you in advance for the help :) 

```
// swift-interface-format-version: 1.0
// swift-compiler-version: Apple Swift version 5.3.1 (swiftlang-1200.0.41 clang-1200.0.32.8)
// swift-module-flags: -target arm64-apple-ios12.0 -enable-objc-interop -enable-library-evolution -swift-version 5 -enforce-exclusivity=checked -O -module-name Sodium
import Clibsodium
import Foundation
@_exported import Sodium
`  ``

**Comment by simonpierreroy** [comment]
I was able to do it by using `@_implementationOnly import Clibsodium` and renamed the Sodium struct to `SodiumSwift` to remove confusion in the `.swiftinterface`. Also removed all referenced to headers not part of the `Clibsodium` XCFramework.

Here is the final solution.

It could be great to implement this in the repo to remove a lot of compiling issues for more complicated project structure :)

[swift-sodium-ios.zip](https://github.com/jedisct1/swift-sodium/files/5647789/swift-sodium-ios.zip)

**Comment by markshiz** [comment]
Are there no plans to support XCFrameworks?  We are interested in this.

**Comment by adamsousa** [comment]
Any updates on this?
