### ISSUE TITLE
arm64 required

### ISSUE THREAD

**Issue by utdrmac** [jedisct1/swift-sodium#229]
Trying to install your package as part of a dependency on another library using carthage.

```
carthage update --platform macOS
...
...
error: The linked library 'libsodium-osx.a' is missing one or more architectures required by this target: arm64. (in target 'Sodium_OSX' from project 'Sodium')
```

I'm not looking to build for apple silicon yet. Is there some flag I can pass to ignore arm64? My target install base is anyone running 10.15+

**Comment by utdrmac** [comment]
```
*** Downloading swift-sodium.framework binary at "0.8.0"
***  Skipped installing swift-sodium.framework binary due to the error:
	"Incompatible Swift version - framework was built with 5.0 (swiftlang-1001.0.69.5 clang-1001.0.46.3) and the local version is 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)."
```

**Comment by jedisct1** [comment]
There’s no `libsodium-osx.a` file in the project, so it looks like you have an old version, or maybe two versions installed at the same time?

Also, does Carthage even work with Xcode 12 yet? [It doesn’t seem so](https://github.com/Carthage/Carthage/blob/5aeba0423006f6589656b26e9d7c8ae49c9aa5d7/Documentation/Xcode12Workaround.md), so I’d recommend [using the Swift Package](https://github.com/jedisct1/swift-sodium#usage) instead.

This is completely untested, but even CocoaPods seem to be fine now,
