### ISSUE TITLE
Can't figure out how to use Scrypt, no documentation

### ISSUE THREAD

**Issue by peradym** [jedisct1/swift-sodium#23]
I have tried digging through the header files in order to determine how to use Scrypt without any success. I did find this:
```SODIUM_EXPORT
int crypto_pwhash_scryptsalsa208sha256_str(char out[crypto_pwhash_scryptsalsa208sha256_STRBYTES],
                                           const char * const passwd,
                                           unsigned long long passwdlen,
                                           unsigned long long opslimit,
                                           size_t memlimit);
```
But I cannot figure out how to use it. Node.js returns "is not a function". I am using `var sodium = require("sodium").api;`.

How can I use the Scrypt implementation with this library?

**Comment by peradym** [comment]
Sorry, but I posted this on the wrong library. This was meant for node-sodium.

**Comment by jedisct1** [comment]
I'm a bit confused.

This is a library for Swift, but you're quoting C code and talking about a problem in Javascript? :/

**Comment by jedisct1** [comment]
Ahaha, ok, no worries :)

**Comment by peradym** [comment]
I am also using swift-sodium and it's working great! Scrypt and all. Thanks for putting this together.

**Comment by jedisct1** [comment]
Good to hear!
