### ISSUE TITLE
Swift Sodium 0.9.1 with Swift Package Manager on ARM64/M1, Xcode 12.3, Big Sur 11.1

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/swift-sodium#231]
I've been teaching the use of Swift Sodium with Cocoapods, now I'm using an M1 Mac and using the Swift Package Manager and latest version of SS, 0.9.1.

Whenever I use it to create command line apps in Big Sur 11.1, I noticed that although it creates a target (that also seems to work), I see the following warning:

```Skipping duplicate build file in Copy Files build phase: /Users/john/Library/Developer/Xcode/DerivedData/myApp/SourcePackages/checkouts/swift-sodium/Clibsodium.xcframework/macos-arm64_x86_64/libsodium.a```

Only seems to occur with SPM, any idea how to resolve?

**Comment by johnalanwoods** [comment]
Confirmed this occurs with empty project too.

```
Showing Recent Messages
Skipping duplicate build file in Copy Files build phase: /Users/john/Library/Developer/Xcode/DerivedData/project/SourcePackages/checkouts/swift-sodium/Clibsodium.xcframework/macos-arm64_x86_64/libsodium.a
```

I have looked at the copy files phase and can't see anything to change.

**Comment by plananderson** [comment]
Looks like this is related to this https://github.com/jedisct1/swift-sodium/issues/230#issuecomment-745179995

**Comment by johnalanwoods** [comment]
Spent some time troubleshooting this, seems to be a Swift Package Manager issue.

**Comment by johnalanwoods** [comment]
@jedisct1  - are you seeing this on your DTK?

**Comment by jedisct1** [comment]
I've never noticed anything like that, but maybe I didn't look at the right place :)

Does it prevent the application from compiling, launching or being packaged?

**Comment by johnalanwoods** [comment]
@jedisct1 no, it compiles and works :)

It's just a warning, it's weird though, even on a "hello world" type app, just importing via SPM and including an "import Sodium" - then this warning occurs.

On both my M1 machines.

**Comment by plananderson** [comment]
@johnalanwoods try to `Archive` the project.

**Comment by johnalanwoods** [comment]
@plananderson, archive works, but warning remains.

**Comment by plananderson** [comment]
🤔

**Comment by johnalanwoods** [comment]
Think this is a Swift-Sodium issue, not seeing it in any other projects using other libs.

**Comment by FabioTacke** [comment]
I get this warning multiple times on each build. Swift-Sodium 0.9.1, SPM, Intel based Mac, Xcode 12.4, macOS 11.2.3

**Comment by ppamorim** [comment]
Also happening on Catalina.

**Comment by johnalanwoods** [comment]
@jedisct1  - no longer occurs in Big Sur 11.4 with Xcode Version 12.5 (12E262).

Closing.
