### ISSUE TITLE
Create Documentation

### ISSUE THREAD

**Issue by blochberger** [jedisct1/swift-sodium#24]
I know there is [documentation for libsodium](https://download.libsodium.org/doc/) but it would be nice to have some documentation for the Swift classes that integrates nicely with Xcode, see [Swift Documentation](http://nshipster.com/swift-documentation/).

**Comment by jedisct1** [comment]
Thanks, @jnross !

**Comment by jnross** [comment]
I confirmed that these docs make it through the Carthage build process and appear in my project that consumes the framework :)

**Comment by jedisct1** [comment]
Excellent :)
