### ISSUE TITLE
xchacha20poly1305ietf

### ISSUE THREAD

**Issue by olimdzhon** [jedisct1/swift-sodium#240]
hi, how can i use sodium.aead.xchacha20poly1305ietf.encrypt(message: dataString, secretKey: cek, additionalData: protectedHeader) in order to make javascript like encryption 
<img width="390" alt="Screen Shot 2021-01-19 at 10 17 12 PM" src="https://user-images.githubusercontent.com/22055973/105069730-26fa3400-5aa4-11eb-8de1-2034761e5889.png">

**Comment by jedisct1** [comment]
You can call `Aead.XChaCha20Poly1305Ietf.encrypt(message: Bytes, secretKey: Key, additionalData: Bytes? = nil) -> (authenticatedCipherText: Bytes, nonce: Nonce)?`.

This returns the ciphertext and the nonce (manually creating the nonce before is not necessary, the function does it for you).
