### ISSUE TITLE
There's no revision to checkout to verify xcframework build

### ISSUE THREAD

**Issue by own2pwn** [jedisct1/swift-sodium#243]
in readme, you're refering to revision `a08a945c589462f524efddbc8d62427bb002bb6a` which doesn't seem to exist

**Comment by jedisct1** [comment]
You obviously checked out the libsodium repository, right?

**Comment by own2pwn** [comment]
Completely missed I was trying to checkout wrong repo.. Sorry for that!

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium/tree/a08a945c589462f524efddbc8d62427bb002bb6a
