### ISSUE TITLE
Clibsodium without `SODIUM_LIBRARY_MINIMAL`?

### ISSUE THREAD

**Issue by aidantwoods** [jedisct1/swift-sodium#248]
Would there be any issue, in principle, with adjusting the precompiled libsodium to be a non-minimal build? At the moment I believe that `SODIUM_LIBRARY_MINIMAL 1` is set, and so some parts of Clibsodium are not available.

i.e. all of these are not currently available when importing `Clibsodium`

https://github.com/jedisct1/swift-sodium/blob/1d51e8eb8a99638166aea863e7a71d568b5a06e6/Sodium/libsodium/sodium_lib.h#L56-L67

**Comment by HashMapsData2Value** [comment]
I would also like to have access to these libraries, specifically crypto_scalarmult_ed25519

**Comment by jedisct1** [comment]
```sh
git clone -b stable https://github.com/jedisct1/libsodium
cd libsodium
env LIBSODIUM_FULL_BUILD=1 ./dist-build/apple-xcframework.sh
```

It will be placed into `libsodium-apple`.
