### ISSUE TITLE
To encrypt message with 64 char public key in Swift - MacOS App

### ISSUE THREAD

**Issue by chillin0531** [jedisct1/swift-sodium#252]
I'm developing a MacOS app in which I need to encrypt a data and send to our server in JSON format. Our server has provided the public key with length of 64 characters. We could able to completed the encryption process with same key in Windows app and its working fine. I have issues in integrating the same functionality in Swift. 

`

        let sodium = Sodium()
        let publicKey = "<My Public Key>".bytes
        let message = "Test Message".bytes
        let encryptedMessage = sodium.box.seal(message: message, recipientPublicKey: publicKey)  //Always returns nil
        if(encryptedMessage != nil){
            print("Data available...")
        }
        else{
            print("Data NOT available")
        }
    }`

**Comment by jedisct1** [comment]
Hi!

Public keys are 32 bytes long and are binary data.

Since you are referring to "64 characters", maybe what you have is encoded in hexadecimal?

**Comment by chillin0531** [comment]
Thanks @jedisct1 
I have converted the public key from hex to binary and able to do the encryption.
And my server also decrypts the text.

>   let sodium = Sodium()
  let publicKey = sodium.utils.hex2bin("<My Public Key>)
  let message = "Test Message".bytes
  let encryptedMessage = sodium.box.seal(message: message, recipientPublicKey: publicKey!)
  if(encryptedMessage != nil){
      print("Encrypted message : ")
      print(sodium.utils.bin2base64(encryptedMessage!, variant: .ORIGINAL_NO_PADDING) as Any)
  }
  else{
    print("Data NOT available")
  }
