### ISSUE TITLE
Missing function for returning a public key corresponding to a given secret key

### ISSUE THREAD

**Issue by timlangner** [jedisct1/swift-sodium#253]
Hi!
I would like to generate a corresponding public key to a given secret key but it seems like a function like this is not implemented in the library yet. I would highly appreciate if this gets added soon. A similar function which does this is implemented in the [tweetnacl-js ](https://github.com/dchest/tweetnacl-js#naclboxkeypairfromsecretkeysecretkey) library.

Kind regards
Tim

**Comment by jedisct1** [comment]
Hi Tim!

It's there :)

`keypairFromSeed()` returns a key pair from the seed, which is the secret key.
