### ISSUE TITLE
Missing function to seal a message with a recipient public key and a nonce

### ISSUE THREAD

**Issue by timlangner** [jedisct1/swift-sodium#254]
Hi!
I would like to seal a message with a given public key and a nonce. However, it seems like that I cannot provide my own nonce.

I'm using `sodium.box.seal(message: Bytes, recipientPublicKey: Box.PublicKey)` right now which doesn't take a nonce as an argument.

A [similar function](https://github.com/TogaTech/tweetnacl-js-sealed-box#naclsecretboxmessage-nonce-key) which does this is implemented in the [tweetnacl-js-sealed-box](https://github.com/TogaTech/tweetnacl-js-sealed-box) library.

Kind regards
Tim

**Comment by johnalanwoods** [comment]
`sealed-box` is really just `x25519` key agreement in an ephemeral:static context with XSalsa20-Poly1305.
As you're probably aware, reuse of a (key, nonce) tuple with XSalsa/XChaCha results in a catastrophic loss of security.

Swift-sodium, intentionally hides the nonce management as an implementation detail.

It's trivial to extend behaviour if you need to override, but why?

**Comment by timlangner** [comment]
I agree that a reuse of a nonce results in a catastrophic loss of security. But for my purposes I need to know the exact nonce which is used to encrypt a message with a public key and add it to my encrypted file data so it supports the decryption process on my other ends.

Is there a way to achieve this?

**Comment by johnalanwoods** [comment]
Yep just change this line to use your custom nonce:

https://github.com/jedisct1/swift-sodium/blob/8f94369541f5c048a9190a7095a941d4419f002d/Sodium/Generators/NonceGenerator.swift#L17

**Comment by johnalanwoods** [comment]
Ah my mistake, anonymous boxes (unlike the authenticated variant) use the following structure:

`ephemeral_pk ‖ box(m, recipient_pk, ephemeral_sk, nonce=blake2b(ephemeral_pk ‖ recipient_pk))`

Which is why you don't see a nonce call, the node is the blake2b digest of the concatenation of the ephemeral_pk and the recipient_pk - which due to the ephemeral nature of the former will always be random.

So, you can strip the last `crypto_box_curve25519xsalsa20poly1305_NONCEBYTES` i.e. `24 Bytes` from the anonymous cipher text, or you can reconstitute it yourself.

Alternatively there is a static:static variant which allows nonce specification.

@jedisct1 - let me know if I'm off base with this advice, but I think I'm correct.

**Comment by johnalanwoods** [comment]
EDIT: actually the better way to do it is strip from the anonymous cipher text the prefix representing `ephemeral_pk`.

Then hash it concatenated with your recipients pk.

Then you have the nonce.

**Comment by jedisct1** [comment]
In Swift, `Box.seal()` maps to the traditional `crypto_box()` construction, not sealed boxes.

The output is the concatenation of the nonce and the ciphertext.

So, if you want the nonce, just extract the 24 first bytes.

**Comment by jedisct1** [comment]
The anonymous one, but I don't think this is what the OP is referring to.

**Comment by timlangner** [comment]
Your explanation definitely clarifies some things for me. So if I understand this correctly the `sodium.box.seal(message: Bytes, recipientPublicKey: Box.PublicKey)` function appends the random generated nonce before the ciphertext? So if I extract the 24 first bytes from the encrypted message (ciphertext) I have the nonce, right?

**Comment by johnalanwoods** [comment]
@timlangner - first are you using the anonymous or authenticated encryption?

**Comment by jedisct1** [comment]
I don't think it makes a difference. The nonce is encoded in the first 24 bytes in both cases.

**Comment by timlangner** [comment]
I'm using anonymous encryption

**Comment by johnalanwoods** [comment]
@timlangner in that case you need to do what I suggest above.

First 24 Bytes is only the nonce with authenticated boxes.

With sealed boxes you need to calculate it as:

`nonce=blake2b(ephemeral_pk ‖ recipient_pk))`


Where you know the `recipient_pk` (your sending to it) and you know the `ephemeral_pk` it's the first 32 Bytes of the cipher text.

**Comment by timlangner** [comment]
It's good to know that the nonce is not encoded in the first 24 bytes in both cases. That makes a difference in my decryption process.

In the [tweet-nacl-js-sealed-box library](https://github.com/TogaTech/tweetnacl-js-sealed-box#naclsealedboxnoncelength--24) used for the frontend the nonce is always 24 bytes long.
