### ISSUE TITLE
Ambiguous use of 'encrypt(message:secretKey:additionalData:)'

### ISSUE THREAD

**Issue by gbmsimoes** [jedisct1/swift-sodium#257]
I'm trying to use this library to encrypt a pin.
When I call this function `let encryptedPin = sodium.aead.xchacha20poly1305ietf.encrypt(message: pin.bytes, secretKey: secretkey)` I'm getting an `Ambiguous use of 'encrypt(message:secretKey:additionalData:)'`

From looking around, I'm getting some information regarding using a selector to remove the ambiguity.
Can someone provide help?
Maybe share the correct signature for this?

Thank you!

![Screenshot 2022-09-02 at 12 43 48](https://user-images.githubusercontent.com/8104391/188132507-bf94d034-780a-44b9-bcf9-35b5eba018ba.png)

**Comment by jedisct1** [comment]
The prototypes are:

```
public func encrypt(message: Bytes, secretKey: Key, additionalData: Bytes? = nil) -> Bytes?
```


and

```
public func encrypt(message: Bytes, secretKey: Key, additionalData: Bytes? = nil) -> (authenticatedCipherText: Bytes, nonce: Nonce)?
```

If returning `Bytes`, the authenticator is attached (this is usually what you want). If returning a tuple, the ciphertext and the authenticator are returned separately.

With just `let encryptedPin` and no type given or inferred for `encryptedPin` there's no way to know which function you want to call.
