### ISSUE TITLE
 GM/T Series Chinese Standard Algorithms Support

### ISSUE THREAD

**Issue by gopiprasanthpotipireddy** [jedisct1/swift-sodium#259]
Hi , I was looking for GM/T Series chinese national standard algorithms (SM2,SM3,SM4) support in Swift . Is there any plan to implement those here.

**Comment by jedisct1** [comment]
Hi!

Unfortunately, there are no plans to implement these in this project. I understand that they are required for compliance reasons, but from a security and performance perspective, these algorithms would be redundant over the ones we currently have.

That being said, the [GMObjC project](https://github.com/muzipiao/GMObjC) may be useful.
