### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by tylerbrandt** [jedisct1/swift-sodium#261]
Hi,

This project seems to be pretty active based on commit activity, but the latest release was 0.9.1 in December 2020, so we're not sure how best to proceed with including it in our project. Do you intend consumers to stay on that release until a new one is cut, or would you advise referring to a master branch commit directly (we're using SPM)?

Best,
Tyler

**Comment by jedisct1** [comment]
If you're using SPM, pick a master branch commit.

**Comment by tylerbrandt** [comment]
Ok, thanks!
