### ISSUE TITLE
[help needed] Import as pod 

### ISSUE THREAD

**Issue by mkaczmarczyk1986** [jedisct1/swift-sodium#269]
Hi,
I have a problem with library. I've mobile app which I write for customer. As new feature I've to add external library (private library written by external company) which includes Sodium. When I'm importing it as it is described in readme everything is working well but unfortunately I'm build app with ci/cd and I can't open xcode there to add external SPM package (via File -> Swift packages etc.). So I've tried to add this as a pod in podfile and install it. But I have problem there. After add this to podfile:
![image](https://github.com/user-attachments/assets/1cb4e429-355d-46b9-8b13-6f4bad4bd7f4)
I've got error in this external library:
![image](https://github.com/user-attachments/assets/62477c17-89af-43bf-b711-79238cabcf5c)
So I've added xcframework from source code in xcode (I will move it later to podfile but for test I've done it this way):
![image](https://github.com/user-attachments/assets/bf49d7fe-af93-412e-872f-c094a357ee65)

And after that I've got error:
![image](https://github.com/user-attachments/assets/f4fc1045-5d7e-4e6a-bca8-c965f2f8c46b)

So I have some questions:
* Is there any solution to make this working? 
* Should I wrote to external vendor which is implementing library using Sodium to fix project
* Am I doing something wrong importing it as a pod? 
* Or there is any solution that I can import Sodium as Swift Package  without opening xcode. I've been looking in stackoverflow, in apple forum, in swift forum solutions but I didn't found nothing
I'll be very glad if someone could point me what I'm doing wrong or how to make it working with ci/cd when I can't open xcode and add this manually.

**Comment by johnalanwoods** [comment]
Use `swift package resolve` to pull packages from command line which are defined in Package.swift

**Comment by mkaczmarczyk1986** [comment]
Thank You vey much for response but I don't if I can do it. I don't have Package.swift in my project (it is created with cocoapods). So I can't run `swift package resolve`. All tutorials which I've seen are made with path open xcode, go to file, and add package dependency. This can't be done with CI/CD where project is created after git checkout.

**Comment by johnalanwoods** [comment]
no probs - I'd move away from Cocoapods and then move to define a Package.swift, then you can do the same thing you do in Xcode, but programatically
