### ISSUE TITLE
Is there a mistake in README?

### ISSUE THREAD

**Issue by casevictor** [jedisct1/swift-sodium#36]
In the **Public-key authenticated encryption** example:

```
let messageVerifiedAndDecryptedByBob = sodium.box.open(encryptedMessageFromAliceToBob,
     senderPublicKey: bobKeyPair.publicKey,
     recipientSecretKey: aliceKeyPair.secretKey)
```

Would not be ?
```

let messageVerifiedAndDecryptedByBob = sodium.box.open(encryptedMessageFromAliceToBob,
      senderPublicKey: aliceKeyPair.publicKey,
      recipientSecretKey: bobKeyPair.secretKey)
```

**Comment by blochberger** [comment]
I would agree. I wanted to validate this with an additional test case but in both cases the decrypted message is equal. This is probably due to the ECDH key agreement, where `alice.secretKey` × `bob.publicKey` = `alice.publicKey` × `bob.secretKey`.

**Comment by jedisct1** [comment]
Hi Victor,

You are totally correct. As pointed out by @blochberger , the shared secret ends up being the same, but in the context of that example, it doesn't make sense the decrypt the message with the sender SK.

This has been fixed. Thanks!

**Comment by blochberger** [comment]
Just for reference the associated commit is 6025a247fd436112363b71f51948a12efe1805e9.

The fix is not in `master`, but I assume that `swift-3` becomes `master` soon, so it is probably intentional?

**Comment by jedisct1** [comment]
Yep. Now that swift-3 has been officially released, it will become the master branch soon.
