### ISSUE TITLE
Support to Xcode 8 and Swift 3

### ISSUE THREAD

**Issue by casevictor** [jedisct1/swift-sodium#37]
Hello folks, 
I know that @jedisct1 is actually working officially at the _swift-3_ branch, and it will be release soon.
But for anyone else that need the support for "yesterday" I took the freedom to create a fork with full support to Xcode 8 and Swift3. I did some tests and tricks today and everything seems fine..

Check the repo
https://github.com/casevictor/swift-sodium/tree/swift-3

@jedisct1 thanks for the amazing job!

**Comment by jedisct1** [comment]
The master branch is now Swift-3 only.

Thanks!

**Comment by gpalomar** [comment]
Hi @jedisct1 !
I'm trying to install swift-sodium using cocoapods and all the code it installs is not in swift 3. Can you explain me what I'm doing wrong and how can I fix it?

If it helps, my Podfile looks like this:
`platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
 
target 'myApp' do
    pod 'Fabric'
    pod 'Crashlytics'
     pod 'Sodium'
end`

Thanks Frank!
