### ISSUE TITLE
Sodium Pod Swift 3

### ISSUE THREAD

**Issue by gpalomar** [jedisct1/swift-sodium#38]
Hi!
I'm downloading the Sodium library using CocoaPods.
`source 'https://github.com/CocoaPods/Specs.git'`

`platform :ios, '8.0'`
`inhibit_all_warnings!`

`use_frameworks!`

`target 'my_app' do`
`    pod 'Fabric'`
`    pod 'Crashlytics'`
`    pod 'Sodium'`
`end`

All installed correctly but when I launch the `.xcworkspace`Xcode8 shows me this alert:
<img width="422" alt="captura de pantalla 2016-10-01 a les 13 50 49" src="https://cloud.githubusercontent.com/assets/3463553/19013889/1b6dbc58-87de-11e6-9135-2c5735fff63b.png">

I don't understand why this happens because in repository readme says **Swift 3 is now the default**.

What can I do?

Thanks!

**Comment by ChaosCoder** [comment]
It's because there was not a new release version of this library, so the pod still refers to an old commit (where swift-3 was not yet merged). 

Until a new version is released you could tell your Podfile to use the current version on the master branch by just defining:
```
pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium.git'
```

**Comment by gpalomar** [comment]
Thanks for the reply @ChaosCoder 
This was what I thought, but using this wait to get the framework, I'm still getting the same problem. Xcode tells me that Sodium shoud be unlocked to convert it to Swift 3.

After days of silence in this post, I'm sure that it's my fault, but I don't know how to resolve it :worried:

**Comment by ChaosCoder** [comment]
Did you set the library to use swift 3 as compiler setting?

Both top answers can be used, the top one is permanent, the second one has to be done after each `pod install`: http://stackoverflow.com/questions/38446097/xcode-8-beta-3-use-legacy-swift-issue

**Comment by gpalomar** [comment]
@ChaosCoder you are the MVP! :smiley:

Using [this](http://stackoverflow.com/a/38466703), Sodium works perfectly in Xcode8.
Thanks a lot!!
