### ISSUE TITLE
Swift 3 Support 

### ISSUE THREAD

**Issue by pgbear** [jedisct1/swift-sodium#40]
I created a test project with sodium library added using cocoapods. I was able to install version 0.2.0. But when I tried to build XCode 8 throws swift versioning errors. I can manually fix those errors to build the project but is it possible to fix them ahead 
[Test.zip](https://github.com/jedisct1/swift-sodium/files/528549/Test.zip)
?

**Comment by blochberger** [comment]
Do the suggestions made in #38 help?

**Comment by pgbear** [comment]
Great! I had to mention git branch as well configure to not use the legacy swift version.

`pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium.git'`
```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```
