### ISSUE TITLE
What algorithm is used when keys are created?

### ISSUE THREAD

**Issue by netgfx** [jedisct1/swift-sodium#41]
Do you use Curve25519? If not using it by default, but it is supported, how do we change it to that?

Thanks.

**Comment by mmackowiak** [comment]
Hey, `swift-sodium` is based on `libsodium` so you can find more details on this site:
https://download.libsodium.org/doc/

Regarding your question specifically - yes, key exchange is done using X25519 (so based on Curve25519):
https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption.html (bottom of page).

**Comment by netgfx** [comment]
thanks, greatly appreciate it.
