### ISSUE TITLE
Error when using Sodium with Cocoapods

### ISSUE THREAD

**Issue by stevemu** [jedisct1/swift-sodium#46]
Hello guys,

This is my pod file:
![screen shot 2016-10-27 at 11 39 19 am](https://cloud.githubusercontent.com/assets/7694000/19774120/02e76be6-9c3a-11e6-90cc-6283c1405d0c.png)

I did "pod install"

When I imported Sodium in the project, it gives me those error:
![screen shot 2016-10-27 at 11 39 59 am](https://cloud.githubusercontent.com/assets/7694000/19774163/1e6dc66c-9c3a-11e6-971a-8fa31b7f9914.png)

I'm using Xcode 8 and Swift 3.

Can you help, please?

**Comment by blochberger** [comment]
Does the suggestion made by @pgbear in https://github.com/jedisct1/swift-sodium/issues/40#issuecomment-253782431 help?

The issues #38 and #40 might be related.

**Comment by stevemu** [comment]
It worked! Thanks, @blochberger !
