### ISSUE TITLE
iOS and OSX Example apps

### ISSUE THREAD

**Issue by ramki1979** [jedisct1/swift-sodium#5]
In my local branch, I have added iOS and OSX app using the build frameworks.
But the app didn't have any thing than just

import Sodium
let sodium = Sodium()!

If any one having some example code with UI that want to include, let me know, I will add the code and will make a pull request.

Or just let me know, I will merge the sample apps as it is and make a pull request.

**Comment by ramki1979** [comment]
Added to master, closing this issues.
Have time I will update the Example project to include UI

**Comment by jedisct1** [comment]
Thank you so much for your help!
