### ISSUE TITLE
Add wrapper for ChaCha20 functions

### ISSUE THREAD

**Issue by bclausdorff** [jedisct1/swift-sodium#55]
It would be nice, would the ChaCha20 functions also get a wrapper.

**motivation**
a) To make them accessible just by including the `Sodium.framework` to one's project (right now, directly accessing the raw C-functions results in linker errors).
b) To make it easier to use them. Not only could the pointers nicely be wrapped, but also some logic could be implemented to help users handle e.g. data-streams.

Right now, one could use those unaccessible C-functions by including the respective `libsodium.a` file to one's project. But that's where motivation b) kicks in.

**Comment by mmackowiak** [comment]
I've just run into linker issue for ChaCha20+Poly1305. Trying to figure it out, but with no luck so far...
