### ISSUE TITLE
Cocoa pods support

### ISSUE THREAD

**Issue by SnitramDev** [jedisct1/swift-sodium#56]
Please add support for cocoa pods. It's way easier to manage dependencies.
Great job!
Thanks!

**Comment by jedisct1** [comment]
Hi!

Swift-sodium can currently be added as a dependency using Carthage.

I don't use Cocoapods, so even if I try to write a podfile, it's bound to be terrible, untested and constantly out of date :)

But pull requests from people actually using it and willing to maintain the pod file and everything else cocoapods support requires would be more than welcome.

**Comment by blochberger** [comment]
Maybe the solution provided in https://github.com/jedisct1/swift-sodium/issues/40#issuecomment-253782431 does help?

See also #38 and #46.
