### ISSUE TITLE
Generate HMAC

### ISSUE THREAD

**Issue by SnitramDev** [jedisct1/swift-sodium#57]
Generate HMAC from string and bytes using 128, 256, 512.
Thanks

**Comment by jedisct1** [comment]
Can you clarify the problem you are trying to solve?

**Comment by SnitramDev** [comment]
How to create an HMAC using the SHA256 algorithm? Is it supported?

**Comment by jedisct1** [comment]
https://download.libsodium.org/doc/advanced/hmac-sha2.html

**Comment by jedisct1** [comment]
This construction is available in the C library as a low-level function: https://download.libsodium.org/doc/advanced/hmac-sha2.html

It is not exposed in Swift-Sodium, but unless you explicitly needs this algorithm, BLAKE2 will achieve the same result while being faster:

https://github.com/jedisct1/swift-sodium#keyed-hashing

**Comment by SnitramDev** [comment]
Unfortunately, I really need that algorithm... Thanks for everything. Great job with the library.

**Comment by mmackowiak** [comment]
@SnitramDev, is your project Swift only?

**Comment by jamesstidard** [comment]
@mmackowiak @jedisct1 Would either of you be able to give an example of using the C APIs through this project? Unless I'm misunderstanding @mmackowiak's comment.

I'm using a `Xcode-Swift` project with dependancies managed by `Carthage`. So if it's possible to get to the advanced API of libsodium (like the elliptic curve) through `Swift-Sodium`, I would prefer this. It would make my dependancy management easier and Carthage also alerts you when packages are out of date.

Thanks
