### ISSUE TITLE
Not compatible with swift 3

### ISSUE THREAD

**Issue by WANGjieJacques** [jedisct1/swift-sodium#59]

**Comment by jedisct1** [comment]
Hi,

What exact issue are you experiencing?

The current code was written for Swift3, and actually works only on Swift3.

**Comment by WANGjieJacques** [comment]
simply using `pod 'Sodium'`  doesn't work, I solve the problem by using `pod 'Sodium', :git => 'https://github.com/jedisct1/swift-sodium.git'`, maybe you need to update the cocoapods.

**Comment by jedisct1** [comment]
The Pod has been updated, but I don't use Cocoapods, so I can't guarantee that it works :)
