### ISSUE TITLE
add AuthenticationKey.

### ISSUE THREAD

**Issue by WANGjieJacques** [jedisct1/swift-sodium#65]
https://github.com/abstractj/kalium/blob/5c9c0953bd49840c27490f51edc301515859151f/src/main/java/org/abstractj/kalium/keys/AuthenticationKey.java
I can not find something like AuthenticationKey class in swift-sodium. I would like to create a pull request for this, but I'm not sure if it is a good idea.

**Comment by jedisct1** [comment]
So, that's `crypto_auth`?

Sure, that could be a useful addition.
