### ISSUE TITLE
Can someone please show example of exactly how to add sodium as a framework target??

### ISSUE THREAD

**Issue by Jcarto** [jedisct1/swift-sodium#68]
Add `Sodium.framework` as a dependency to your project...???
Don't know how to do this?

**Comment by ianyh** [comment]
I would suggest using either [CocoaPods](https://cocoapods.org/) or [Carthage](https://github.com/Carthage/Carthage).

For the former you can add
```ruby
pod 'Sodium', '~> 0.3'
```
to your `Podfile`. For the latter you can add
```
github "jedisct1/swift-sodium" ~> 0.3
```
to your `Cartfile`.

**Comment by blochberger** [comment]
If you do not use CocoaPods or Carthage, you can also simply drag'n'drop `Sodium.xcodeproj` to your project in Xcode.

**Comment by krischik** [comment]
@ianyh Tried that. Gives me:

```sh
[!] Unable to determine Swift version for the following pods:

- `Sodium-library` does not specify a Swift version and none of the targets (`…`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod
```
