### ISSUE TITLE
[Feature Request] Add SPM support

### ISSUE THREAD

**Issue by gperdomor** [jedisct1/swift-sodium#69]
Add support for swift package manager please :D

**Comment by kpernyer** [comment]
I second that. Please

**Comment by pixelspark** [comment]
This shouldn't be too difficult. The repository should contain a Package.json that lists 'libsodium' as a C-target (which requires a specific directory lay-out which may or may not already conform) and 'SwiftSodium' as a Swift module.

See:
* https://github.com/apple/swift-package-manager/blob/master/Documentation/Usage.md#c-language-targets
* https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageDescriptionV4.md#targets

**Comment by pixelspark** [comment]
Have tried making libsodium into a Swift package (since the Swift sauce can then use that as a dependency) - see https://github.com/pixelspark/libsodium. Unfortunately the package manager refuses to link to the included libsodium.a binary. Ideas?

**Comment by kpernyer** [comment]
We took a look at that too, but couldn’t figure it out

**Comment by xc19** [comment]
@gperdomor @kpernyer @pixelspark 
you can try to use this project https://github.com/xc19/swift-sodium-spm,
it can't support swift package manager.

**Comment by nixberg** [comment]
Hey @jedisct1,

This should be possible now with SPM4.

Ingredients:
- A `Package.swift` with custom source and exclude paths. [Example](https://github.com/nixberg/swift-sodium/blob/master/Package.swift).
- A system module shim. [Example](https://github.com/nixberg/Clibsodium).
- Semantic Versioning.
