### ISSUE TITLE
Default hash/encrypt methods never changed ?

### ISSUE THREAD

**Issue by gpnuma** [jedisct1/swift-sodium#70]
Just wondering if you would ensure that future implementations or versions of the library will use the exact same algorithms for the same hashing methods, specifically BLAKE2 for generichash or ARGON2i for pwhash, as well as the default secretbox and box encryption/decryption methods based on AES256 and EC if I read your documentation correctly ?
And if that's not the case, will you provide fallback methods to ensure one can still revert to the replaced algorithms ?
The reason for this is if stored in a persistent database, you don't want the encrypted data to be all of a sudden undecipherable due to an update of the library.
Thank you

**Comment by jedisct1** [comment]
Don't worry, these constructions are never going to change until a major revision of the library, which will still provide a compatibility layer with sodium 1.x.
