### ISSUE TITLE
sodium.sign.signature crashes with found nil

### ISSUE THREAD

**Issue by netgfx** [jedisct1/swift-sodium#74]
This is my code:

```
let _message = message.data(using:.utf8)!
let signature:Data?
        if let myKey = self.secretKey {
            if let _signature = self.sodium.sign.signature(message: _message, secretKey: myKey) {
                signature = _signature
            }
            else {
                print("signing failed")
                signature = nil
            }
        }
```
always goes into the `else`. 

If I set it as `self.sodium.sign.signature(message: _message, secretKey: myKey)!` it crashes with `unwrapping optional found nil` error

`message/_message` is not nil (it is an image as base64 string)
`myKey` is not nil and is produced via `let selfKeyPair = self.sodium.box.keyPair()!`

any ideas why it is failing?

**Comment by blochberger** [comment]
You need to use `sodium.sign.keyPair()` for generating a key pair for signing messages, as described in the [documentation](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html). Unfortunately `Sign.SecretKey` and `Box.SecretKey` both are aliases for the `Data` type and therefore will not lead to a compiler error.

The secret keys used for signing are shorter than the secret keys used in `sodium.box` und if the size does not match the `sodium.sign.signature()` method fails.

**Comment by netgfx** [comment]
You are correct I was using the `box`. Thanks for clarifying!
