### ISSUE TITLE
Best format to send public key to server

### ISSUE THREAD

**Issue by netgfx** [jedisct1/swift-sodium#79]
Hello

What is the best way to send the public key produced via `let keyPair = sodium.sign.keyPair()!`
base64, hex string?

The server is running: https://github.com/jedisct1/libsodium-php

**Comment by jedisct1** [comment]
By far the best format is: raw, binary data. Just concatenate both keys.

**Comment by netgfx** [comment]
so convert `Data` to binary data?

**Comment by jedisct1** [comment]
Yes!

And you actually don't need to send both the public and the private key, since the private key's second half is a copy of the public key.

**Comment by netgfx** [comment]
is there a helper function to convert `Data` into binary data so I can send them via an http call? Or is there something in Swift that I can use?

**Comment by blochberger** [comment]
`Data` **is** representing binary data.
