### ISSUE TITLE
crypto_stream_xor implementation.

### ISSUE THREAD

**Issue by WANGjieJacques** [jedisct1/swift-sodium#80]
I can't find `crypto_stream_xor` implementation, but I'm not sure if there is some high-level API for this, if not, I would like to create a pull request for this.

**Comment by jedisct1** [comment]
Hi Jacques,

What is your use case for this?

Would `randomBytes.deterministic()` work for you?

**Comment by WANGjieJacques** [comment]
We need access to the XSalsa20 stream cipher to perform symmetric-key encryption, 
and we don't want to use the authenticated encryption since we don't want authentication in our specific case, and that we only encrypt random data hence attacks specific to stream ciphers will not work.

**Comment by WANGjieJacques** [comment]
Hi, @jedisct1, I'm waiting for your response, I would like to know if it's a good idea to do a pull request for `crypto_stream_xor`, please tell me if what I said is not clear for you, thanks.

**Comment by jedisct1** [comment]
I'm not a big fan of adding functions that are easy to misuse, but with big fat warnings stating that it doesn't include any authentication tags, it should be all right :)

**Comment by jedisct1** [comment]
Merged, thanks!

I updated the documentation and changed the API a little bit to better match the rest of the project.
