### ISSUE TITLE
How to use an existing key pair?

### ISSUE THREAD

**Issue by PietH96** [jedisct1/swift-sodium#82]
Hi,

what is the best way to use an existing key pair which is saved on the local device?

Ist this method the optimal solution?
KeyPair(publicKey: pk, secretKey: sk)
pk and sk are the data of the keys.

Thank´s in advance!

**Comment by jedisct1** [comment]
Hi!

Yes, this is the way to do it!

**Comment by Kapsym** [comment]
Hi

I have an existing public private key as a String with me. I dont see any initialisers in the lib to create a keypair using the existing Keys. Could you please help me out.

**Comment by jedisct1** [comment]
Hi,

Keys are binary data with a fixed length.

They are not passwords.

**Comment by Kapsym** [comment]
Hi

I agree and I am not talking about password. I get the private key from the Server so I save it as a String. Then I need to use this to decrypt the future communications and thats where I am stuck at.

**Comment by PeterHurtenbach** [comment]
Which format is the key which you received from the server? Hex encoded?

**Comment by Kapsym** [comment]
Yes its Hex Encoded.

**Comment by PeterHurtenbach** [comment]
Then you should search an swift method to convert this hex string to binary data...

**Comment by Kapsym** [comment]
Thats there in the sodium Lib in the utilities section :) Used that one to convert to binary data but still unable to decrypt the data. Thanks for the tip though.

**Comment by jedisct1** [comment]
Can you post (not as a comment!) a code snippet somewhere?

How was the key pair created? How was the data encrypted? How are you trying to decrypt it?

**Comment by Kapsym** [comment]
Hi

Please find below the link to the post with the details that you asked. I am not very good on the Server side programming but as per the discussion with my dev, he is using Asymmetric Encryption.

https://stackoverflow.com/questions/46302597/swift-sodium-decrypt-using-private-key

**Comment by jedisct1** [comment]
So, after some Googling, it looks like the server code is written in PHP and uses a library called Halite. I'm not familiar with it, but looking at the code, the function `Cipher::seal()` seems to encode the result as a BASE64 string.

So you need to decode that string in Swift, or not encode it (binary data is going to be faster, smaller and safer).
