### ISSUE TITLE
Package Manager error "error: unsatisfiable"

### ISSUE THREAD

**Issue by TheHawkis** [jedisct1/swift-sodium#88]
Trying to add the dependency to Swift-Sodium but I get a error when building
   error: unsatisfiable

    dependencies: [
        .Package(url: "https://github.com/SwiftyJSON/SwiftyJSON.git", majorVersion: 3, minor: 1),
        .Package(url: "https://github.com/jedisct1/swift-sodium.git", majorVersion: 0),
    ],

The JSON dependency works as intended so I believe that my environment is ok. Tried many combinations of majorVersion and minor version. Even tried:
        .Package(url: "https://github.com/jedisct1/swift-sodium.git", Version(0,0,3, prereleaseIdentifiers: ["beta"])),

I see that only 3 releases exist 0,1  0,2  and 0,3 but I can not figure out how to to use them.

**Comment by TheHawkis** [comment]
I guess this has to do with that I am building on an simulated Linux computer. Not a Mac.
If this is the case can I suggest to enhance the printout from the package manager. "This processor is not supporter" or something.
Or even better add support.

**Comment by pixelspark** [comment]
Probably has to do with the fact that swift-sodium is not yet a Swift Package (e.g. there is no Package.swift in the root). See #69

**Comment by xc19** [comment]
@TheHawkis you can try to use this project https://github.com/xc19/swift-sodium-spm,
it can support swift package manager.

**Comment by jedisct1** [comment]
Is there any way this could be merged into the main tree without side effects?

**Comment by xc19** [comment]
@jedisct1 swift package manager can't support module.modulemap mix,
and swift-sodium/Sodium/libsodium/module.modulemap, it can't build success.

**Comment by TheHawkis** [comment]
Thanks for your responses. Good to know. I will close this.
