### ISSUE TITLE
Update podsec (or 0.3 tag or publish new release) with libsodium.a with armv7s arch slice

### ISSUE THREAD

**Issue by Vladlex** [jedisct1/swift-sodium#90]
Hello!
Due to updating libsodium.a with armv7s arch, do you plan to update either 0.3 tag either podspec file to point to commit with updated lib?
It would be very nice =)
Thanks anyway!

**Comment by opfeffer** [comment]
**bump**. There's been a number of improvements done since the last release.
There a plan around making a new one?

**Comment by ziogaschr** [comment]
It will be indeed nice to update the podspec version, as it causes issues with an App that uses latest code from master branch and a subpackage that has sodium (0.3) as a dependency.

**Comment by jedisct1** [comment]
A couple bindings for recently added functions could really be added before a new version is tagged. 

At least `aead_xchacha20()`, `crypto_secretstream()` and `sodium_pad()`.
