### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by yvbbrjdr** [jedisct1/swift-sodium#91]
I used some low-level functions because they are not provided in the Sodium class. When linking, I got the following error:

```
Undefined symbols for architecture arm64:
  "_sodium_init", referenced from:
      __TToFC7keyacid11AppDelegate11applicationfTCSo13UIApplication29didFinishLaunchingWithOptionsGSqGVs10DictionaryVSC29UIApplicationLaunchOptionsKeyP____Sb in AppDelegate.o
  "_crypto_sign_ed25519_sk_to_pk", referenced from:
      __TTSf4n_g___TFFC7keyacid12LocalProfile10isValidKeyFT_SbU_FGSpVs5UInt8_T_ in LocalProfile.o
  "_crypto_sign_ed25519_secretkeybytes", referenced from:
      __TFC7keyacid14ViewController11viewDidLoadfT_T_ in ViewController.o
      __TFC7keyacid12LocalProfile10isValidKeyfT_Sb in LocalProfile.o
      __TFC7keyacid12LocalProfile15generateKeyPairfT_T_ in LocalProfile.o
  "_crypto_sign_ed25519_publickeybytes", referenced from:
      __TFC7keyacid14ViewController11viewDidLoadfT_T_ in ViewController.o
      __TFC7keyacid12LocalProfile10isValidKeyfT_Sb in LocalProfile.o
      __TFC7keyacid12LocalProfile15generateKeyPairfT_T_ in LocalProfile.o
      __TFC7keyacid13RemoteProfile10isValidKeyfT_Sb in RemoteProfile.o
      __TFC7keyacid13RemoteProfile19curve25519PublicKeyfT_V10Foundation4Data in RemoteProfile.o
ld: symbol(s) not found for architecture arm64
```
I tested many other low-level functions, including crypto_box_easy, crypto_sign_detached, etc, and they are all normal. Only the functions listed above had these linking issues.

It's strange to have sodium_init included...

I am using swift-sodium tag 0.3

**Comment by jedisct1** [comment]
The `crypto_sign_*` functions are not expected to be present in the library shipped with Swift-sodium. This library was built with `--enable-minimal`, which only includes what is required by the high-level APIs. And Swift-Sodium only uses high-level APIs.

I don't have any explanations for `sodium_init()` though. LTO, maybe?

**Comment by yvbbrjdr** [comment]
@jedisct1 So how can I use these functions with my iOS devices? Change to NaOH?

**Comment by jedisct1** [comment]
Just recompile libsodium without the `--enable-minimal` switch.

Get libsodium:
```sh
git clone --branch=stable https://github.com/jedisct1/libsodium.git
```

The script used to create the precompiled files is `dist-build/ios.sh`. Remove the `--enable-minimal` lines from it.

**Comment by yvbbrjdr** [comment]
@jedisct1 Thank you for your help! Actually I was thinking about the same thing and I found that [someone has already done it](https://github.com/zhuhaow/Sodium-framework), though it is not the newest version.
