### ISSUE TITLE
GenericHash::Stream - testStreaming fails sometimes

### ISSUE THREAD

**Issue by psalami** [jedisct1/swift-sodium#92]
SodiumTests.ReadmeTests sometimes (in about 30% of attempts) fails with the following error:

```
Test Case '-[SodiumTests.ReadmeTests testStreaming]' started.
xctest(6198,0x107d243c0) malloc: *** error for object 0x7fb14cd89ae8: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
```

Environment:
iPhone 7 Plus simulator, iOS 10.3

This could possibly be due to the [Stream.state](https://github.com/jedisct1/swift-sodium/blob/master/Sodium/GenericHash.swift#L144) property being an unsafe pointer.

**Comment by jedisct1** [comment]
Any idea on how to fix this?

The state is an unsafe pointer,  but it seems to be properly initialized and freed. I must be missing something obvious.

**Comment by jedisct1** [comment]
Maybe due to the alignment. Does 1ed8ab39b274f1d5e1dd19779fae2d697000d299 improve the situation?

**Comment by blochberger** [comment]
It works for me now. Could reproduce the issue each time I ran the test prior to 1ed8ab39b274f1d5e1dd19779fae2d697000d299.

**Comment by jedisct1** [comment]
Thanks!
